In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [132]:
ROG= 'C:\\AI Equipment Failure Prediction\\data\\15_사출성형_로그 - 복사본.csv'
PROC = 'C:\\AI Equipment Failure Prediction\\data\\15_01_사출성형_공정 - 복사본.csv'

In [6]:
df = pd.read_csv(PROC)

In [13]:
df.shape

(250, 22)

In [ ]:
# dropna() 결측행 제거,   dropna(axis=1) 결측열 제거, dropna(columns=[,,,]) 특정 열의 결측값 제거

In [8]:
df.dropna().shape

(76, 22)

In [12]:
df.dropna(axis=1).shape

(250, 10)

In [14]:
help(df.dropna)

Help on method dropna in module pandas.core.frame:

dropna(
    *,
    axis: Axis = 0,
    how: AnyAll | lib.NoDefault = <no_default>,
    thresh: int | lib.NoDefault = <no_default>,
    subset: IndexLabel | AnyArrayLike | None = None,
    inplace: bool = False,
    ignore_index: bool = False
) -> DataFrame | None method of pandas.DataFrame instance
    Remove missing values.

    See the :ref:`User Guide <missing_data>` for more on which values are
    considered missing, and how to work with missing data.

    Parameters
    ----------
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Determine if rows or columns which contain missing values are
        removed.

        * 0, or 'index' : Drop rows which contain missing values.
        * 1, or 'columns' : Drop columns which contain missing value.

        Only a single axis is allowed.

    how : {'any', 'all'}, default 'any'
        Determine if row or column is removed from DataFrame, when we have
        at least one NA or all NA.

        * 'any' : If any NA values are present, drop that row or column.
        * 'all' : If all values are NA, drop that row or column.

    thresh : int, optional
        Require that many non-NA values. Cannot be combined with how.
    subset : column label or iterable of labels, optional
        Labels along other axis to consider, e.g. if you are dropping rows
        these would be a list of columns to include.
    inplace : bool, default False
        Whether to modify the DataFrame rather than creating a new one.
    ignore_index : bool, default ``False``
        If ``True``, the resulting axis will be labeled 0, 1, …, n - 1.

        .. versionadded:: 2.0.0

    Returns
    -------
    DataFrame or None
        DataFrame with NA entries dropped from it or None if ``inplace=True``.

    See Also
    --------
    DataFrame.isna: Indicate missing values.
    DataFrame.notna : Indicate existing (non-missing) values.
    DataFrame.fillna : Replace missing values.
    Series.dropna : Drop missing values.
    Index.dropna : Drop missing indices.

    Examples
    --------
    >>> df = pd.DataFrame(
    ...     {
    ...         "name": ["Alfred", "Batman", "Catwoman"],
    ...         "toy": [np.nan, "Batmobile", "Bullwhip"],
    ...         "born": [pd.NaT, pd.Timestamp("1940-04-25"), pd.NaT],
    ...     }
    ... )
    >>> df
           name        toy       born
    0    Alfred        NaN        NaT
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Drop the rows where at least one element is missing.

    >>> df.dropna()
         name        toy       born
    1  Batman  Batmobile 1940-04-25

    Drop the columns where at least one element is missing.

    >>> df.dropna(axis="columns")
           name
    0    Alfred
    1    Batman
    2  Catwoman

    Drop the rows where all elements are missing.

    >>> df.dropna(how="all")
           name        toy       born
    0    Alfred        NaN        NaT
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Keep only the rows with at least 2 non-NA values.

    >>> df.dropna(thresh=2)
           name        toy       born
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Define in which columns to look for missing values.

    >>> df.dropna(subset=["name", "toy"])
           name        toy       born
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

In [16]:
print(df.dropna(how='all').shape)

(250, 22)

In [18]:
print(df.dropna(thresh=20).shape)

(162, 22)

In [20]:
df.dropna(thresh=20).head()

,측정시각,불량여부,사이클시간,성형사이클,배럴온도1,배럴온도2,배럴온도3,배럴온도4,호퍼온도,최대사출속도,...,전환위치,계량시간,계량시작점,최대사출압,전환압력,계량시작위치,스크루속도,최소쿠션,계량종료점,감압시간
1,2024-05-07 08:00:17,1,16.56,16.54,210.2,200.8,193.5,187.2,40.2,78.37,...,8.14,4.81,10.49,1211.65,1062.00,10.51,NaN,NaN,63.11,0.32
2,2024-05-07 08:00:34,1,16.58,16.56,210.1,200.7,193.5,187.2,40.2,78.32,...,8.12,4.80,10.53,1209.16,1101.41,10.54,35.38,6.02,63.11,0.32
3,2024-05-07 08:00:51,1,16.62,16.58,210.1,200.6,193.5,187.2,40.2,78.19,...,8.12,4.84,10.78,1228.24,1092.55,10.79,36.35,6.28,63.11,0.33
5,2024-05-07 08:01:25,1,16.62,16.64,210.0,200.4,193.4,187.3,40.1,78.07,...,8.11,4.87,10.92,1261.17,1176.73,10.94,NaN,6.43,63.11,0.33
7,2024-05-07 08:01:59,1,16.62,16.62,210.1,200.3,193.4,187.5,40.0,78.17,...,8.12,4.87,10.87,1285.61,1151.92,10.89,NaN,6.38,63.11,0.32

In [21]:
# 결측 대체 코드

In [22]:
df['스크루속도'].isna().sum()

np.int64(60)

In [28]:
df['스크루속도'].mean().round(1)

np.float64(46.9)

In [29]:
df['스크루속도'].median().round(1)

np.float64(47.4)

In [25]:
pd.set_option('display.max_rows', 20)

In [33]:
demo = df['스크루속도'].fillna(df['스크루속도'].median())
print(demo.isna().sum())

0

In [34]:
pd.NaT

NaT

In [36]:
#실습1 . dropna 행열삭제
#실습2 . dropna 옵션 조절?
#실습3 결측 비율 0.4 이상인 칼럼 (최대사출속도, 감압시간 )제거
#실습4 삭제 손실 비교
#fillna로 평균 중앙값 대체

In [48]:
df.shape

(250, 22)

In [42]:
df.dropna().shape # 결측치가 있는 행 삭제

(76, 22)

In [39]:
df.dropna(axis=1).shape # 결측치가 있는 열 삭제

(250, 10)

In [50]:
df.dropna(how='all').shape  # 모든 값이 결측치인 행만 삭제한 뒤 크기 확인

(250, 22)

In [55]:
df.dropna(thresh=3).shape  # 결측치가 3개 이상인 행 삭제 후 크기 확인

(250, 22)

In [57]:
missing_count = df.isna().sum()

In [58]:
missing_count

측정시각        0
불량여부        0
사이클시간       0
성형사이클       0
배럴온도1       0
         ...
계량시작위치     34
스크루속도      60
최소쿠션       68
계량종료점     109
감압시간      109
Length: 22, dtype: int64

In [59]:
per = missing_count / len(df) * 100
per

측정시각       0.0
불량여부       0.0
사이클시간      0.0
성형사이클      0.0
배럴온도1      0.0
          ...
계량시작위치    13.6
스크루속도     24.0
최소쿠션      27.2
계량종료점     43.6
감압시간      43.6
Length: 22, dtype: float64

In [61]:
celll = pd.DataFrame({'개수': missing_count, '비율': per}).round(2)
celll

         개수    비율
측정시각      0   0.0
불량여부      0   0.0
사이클시간     0   0.0
성형사이클     0   0.0
배럴온도1     0   0.0
...     ...   ...
계량시작위치   34  13.6
스크루속도    60  24.0
최소쿠션     68  27.2
계량종료점   109  43.6
감압시간    109  43.6

[22 rows x 2 columns]

In [62]:
df.dropna(subset=['계량종료점','감압시간']).shape  # 특정 열의 결측치가 있는 행 삭제 후 크기 확인

(141, 22)

In [68]:
df.shape

(250, 22)

In [81]:
log = pd.read_csv(ROG)

In [99]:
log

                측정시각  사출기   배럴온도  사출압력  스크루속도   누적샷  불량여부
0   2024-05-07 08:00  1호기  201.2  1.32   45.1  1200     0
1   2024-05-07 08:01  1호기  201.5  1.33   45.0  1201     0
2   2024-05-07 08:02  1호기    NaN  1.31   44.9  1202     0
3   2024-05-07 08:03  1호기  202.0  0.00   45.2  1203     1
4   2024-05-07 08:04  2호기  199.4  1.28 -999.0   880     0
5   2024-05-07 08:05  2호기  199.8  1.29   42.5   881     0
6   2024-05-07 08:06  2호기  200.2   NaN   42.6   882     0
7   2024-05-07 08:07  1호기  200.9  1.30   42.7   883     0
8   2024-05-07 08:08  2호기  999.0  1.31   42.8   884     1
9   2024-05-07 08:09  A호기  203.1  1.41   47.0  2000     0
10  2024-05-07 08:10  A호기  203.6  1.42 -999.0  2001     0
11  2024-05-07 08:11  A호기  204.0  0.00   47.2  2002     1
12  2024-05-07 08:12  A호기    NaN  1.40   47.1  2003     0
13  2024-05-07 08:13  B호기  198.1  1.35   43.8  1500     0
14  2024-05-07 08:14  B호기  198.6  1.36   43.9  1501     0
15  2024-05-07 08:15  B호기  199.2  1.34    NaN  1502     0

In [98]:
log['사출기']=log['사출기'].fillna(log['사출기'].mode()[0])

In [92]:
log['사출기'].mode()

0    1호기
1    2호기
2    A호기
Name: 사출기, dtype: str

In [101]:
log = log.sort_values('측정시각')

In [103]:
log

                측정시각  사출기   배럴온도  사출압력  스크루속도   누적샷  불량여부
0   2024-05-07 08:00  1호기  201.2  1.32   45.1  1200     0
1   2024-05-07 08:01  1호기  201.5  1.33   45.0  1201     0
2   2024-05-07 08:02  1호기    NaN  1.31   44.9  1202     0
3   2024-05-07 08:03  1호기  202.0  0.00   45.2  1203     1
4   2024-05-07 08:04  2호기  199.4  1.28 -999.0   880     0
5   2024-05-07 08:05  2호기  199.8  1.29   42.5   881     0
6   2024-05-07 08:06  2호기  200.2   NaN   42.6   882     0
7   2024-05-07 08:07  1호기  200.9  1.30   42.7   883     0
8   2024-05-07 08:08  2호기  999.0  1.31   42.8   884     1
9   2024-05-07 08:09  A호기  203.1  1.41   47.0  2000     0
10  2024-05-07 08:10  A호기  203.6  1.42 -999.0  2001     0
11  2024-05-07 08:11  A호기  204.0  0.00   47.2  2002     1
12  2024-05-07 08:12  A호기    NaN  1.40   47.1  2003     0
13  2024-05-07 08:13  B호기  198.1  1.35   43.8  1500     0
14  2024-05-07 08:14  B호기  198.6  1.36   43.9  1501     0
15  2024-05-07 08:15  B호기  199.2  1.34    NaN  1502     0

In [ ]:
log['배럴온도']=log['사출기'].fillna(log['사출기'].mode()[0])

In [105]:
log2 = log['배럴온도']

In [109]:
log2

0     201.2
1     201.5
2     201.5
3     202.0
4     199.4
5     199.8
6     200.2
7     200.9
8     999.0
9     203.1
10    203.6
11    204.0
12    204.0
13    198.1
14    198.6
15    199.2
Name: 배럴온도, dtype: float64

In [108]:
log2.ffill(inplace=True)

0     201.2
1     201.5
2     201.5
3     202.0
4     199.4
5     199.8
6     200.2
7     200.9
8     999.0
9     203.1
10    203.6
11    204.0
12    204.0
13    198.1
14    198.6
15    199.2
Name: 배럴온도, dtype: float64

In [122]:
log3 = log['배럴온도']

In [123]:
log3

0     201.2
1     201.5
2       NaN
3     202.0
4     199.4
5     199.8
6     200.2
7     200.9
8     999.0
9     203.1
10    203.6
11    204.0
12      NaN
13    198.1
14    198.6
15    199.2
Name: 배럴온도, dtype: float64

In [120]:
log3.bfill(inplace=True)

0     201.2
1     201.5
2     202.0
3     202.0
4     199.4
5     199.8
6     200.2
7     200.9
8     999.0
9     203.1
10    203.6
11    204.0
12    198.1
13    198.1
14    198.6
15    199.2
Name: 배럴온도, dtype: float64

In [124]:
log3[0]

np.float64(201.2)

In [127]:
log3[0] = pd.NA

In [128]:
log3.head()

0      NaN
1    201.5
2      NaN
3    202.0
4    199.4
Name: 배럴온도, dtype: float64

In [130]:
log3.ffill(inplace=True).bfill(inplace=True)

0     201.5
1     201.5
2     201.5
3     202.0
4     199.4
5     199.8
6     200.2
7     200.9
8     999.0
9     203.1
10    203.6
11    204.0
12    204.0
13    198.1
14    198.6
15    199.2
Name: 배럴온도, dtype: float64

In [137]:
log = pd.read_csv(ROG)

In [138]:
log

                측정시각  사출기   배럴온도  사출압력  스크루속도   누적샷  불량여부
0   2024-05-07 08:00  1호기  201.2  1.32   45.1  1200     0
1   2024-05-07 08:01  1호기  201.5  1.33   45.0  1201     0
2   2024-05-07 08:02  1호기    NaN  1.31   44.9  1202     0
3   2024-05-07 08:03  1호기  202.0  0.00   45.2  1203     1
4   2024-05-07 08:04  2호기  199.4  1.28 -999.0   880     0
5   2024-05-07 08:05  2호기  199.8  1.29   42.5   881     0
6   2024-05-07 08:06  2호기  200.2   NaN   42.6   882     0
7   2024-05-07 08:07  NaN  200.9  1.30   42.7   883     0
8   2024-05-07 08:08  2호기  999.0  1.31   42.8   884     1
9   2024-05-07 08:09  A호기  203.1  1.41   47.0  2000     0
10  2024-05-07 08:10  A호기  203.6  1.42 -999.0  2001     0
11  2024-05-07 08:11  A호기  204.0  0.00   47.2  2002     1
12  2024-05-07 08:12  A호기    NaN  1.40   47.1  2003     0
13  2024-05-07 08:13  B호기  198.1  1.35   43.8  1500     0
14  2024-05-07 08:14  B호기  198.6  1.36   43.9  1501     0
15  2024-05-07 08:15  B호기  199.2  1.34    NaN  1502     0

In [140]:
lambda : print("hi")

In [141]:
lamda

NameError: name 'lamda' is not defined

In [ ]:
proc.groupby('사출기')['스크루속도'].transform('mean')

In [142]:
f2_l=lambda gift : print(gift)

In [144]:
f2_l('마라탕')

마라탕

In [ ]:
def f3():
    return '안녕'

In [145]:
f3_l = lambda : "안녕"

In [146]:
result = f3_l()

In [148]:
result

'안녕'

In [149]:
f4_l=lambda gift : 'hihi'

In [152]:
result3 = f4_l('사이다')

In [153]:
result3

'hihi'

In [160]:
#람다 함수로 더하기 함수 정의
f = lambda x, y: x + y
result = f(10, 10)
result

20

In [159]:
def d(x):
    return x+10

result = d(10)
print(result)

20

In [162]:
ROG

'C:\\AI Equipment Failure Prediction\\data\\15_사출성형_로그 - 복사본.csv'

In [197]:
log = pd.read_csv('C:\\AI Equipment Failure Prediction\\data\\15_사출성형_로그 - 복사본.csv')

In [203]:
log = pd.read_excel('C:\\AI Equipment Failure Prediction\\data\\사출성형_로그(결측치).xlsx')

In [204]:
def fillnaMean(x):
    return x.fillna(x.mean())

In [174]:
log['스크루속도'] = log.groupby('사출기')['스크루속도'].transform(fillnaMean)

In [205]:
log['스크루속도']

0      45.1
1      45.0
2      44.9
3      45.2
4    -999.0
5      42.5
6      42.6
7      42.7
8      42.8
9      47.0
10   -999.0
11     47.2
12     47.1
13     43.8
14     43.9
15      NaN
Name: 스크루속도, dtype: float64

In [182]:
log = pd.read_csv(ROG)

In [206]:
log['스크루속도'] = log.groupby('사출기')['스크루속도'].transform(
    lambda x : x.fillna(x.mean())
)

In [207]:
log['스크루속도']

0      45.10
1      45.00
2      44.90
3      45.20
4    -999.00
5      42.50
6      42.60
7      42.70
8      42.80
9      47.00
10   -999.00
11     47.20
12     47.10
13     43.80
14     43.90
15     43.85
Name: 스크루속도, dtype: float64

In [192]:
log['사출기'].isna().sum()

np.int64(1)

In [208]:
log2=pd.read_excel('C:\\AI Equipment Failure Prediction\\data\\사출성형_로그(결측치).xlsx', na_values=['999','-999'])

In [217]:
log2

                  측정시각  사출기   배럴온도  사출압력   스크루속도   누적샷  불량여부
0  2024-05-07 08:00:00  1호기  201.2  1.32   45.10  1200     0
1  2024-05-07 08:01:00  1호기  201.5  1.33   45.00  1201     0
2  2024-05-07 08:02:00  1호기    NaN  1.31   44.90  1202     0
3  2024-05-07 08:03:00  1호기  202.0  0.00   45.20  1203     1
4  2024-05-07 08:04:00  2호기  199.4  1.28 -999.00   880     0
5  2024-05-07 08:05:00  2호기  199.8  1.29   42.50   881     0
6  2024-05-07 08:06:00  2호기  200.2   NaN   42.60   882     0
7  2024-05-07 08:07:00  1호기  200.9  1.30   42.70   883     0
8  2024-05-07 08:08:00  2호기    NaN  1.31   42.80   884     1
9  2024-05-07 08:09:00  A호기  203.1  1.41   47.00  2000     0
10 2024-05-07 08:10:00  A호기  203.6  1.42 -999.00  2001     0
11 2024-05-07 08:11:00  A호기  204.0  0.00   47.20  2002     1
12 2024-05-07 08:12:00  A호기    NaN  1.40   47.10  2003     0
13 2024-05-07 08:13:00  B호기  198.1  1.35   43.80  1500     0
14 2024-05-07 08:14:00  B호기  198.6  1.36   43.90  1501     0
15 2024-05-07 08:15:00  B호기  199.2  1.34   43.85  1502     0

In [214]:
log2.groupby('사출기')['스크루속도']

In [215]:
log2['스크루속도'] = log.groupby('사출기')['스크루속도'].transform(lambda x: x.fillna(x.mean()))

In [216]:
log2['스크루속도']

0      45.10
1      45.00
2      44.90
3      45.20
4    -999.00
5      42.50
6      42.60
7      42.70
8      42.80
9      47.00
10   -999.00
11     47.20
12     47.10
13     43.80
14     43.90
15     43.85
Name: 스크루속도, dtype: float64