In [3]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('C:\\AI Equipment Failure Prediction\\data\\14_hydraulic.csv')

In [5]:
qc = pd.read_csv('C:\\AI Equipment Failure Prediction\\data\\14_hydraulic_qc.csv')

In [6]:
df.head()

  냉각기상태 운전부하 밸브상태    온도     진동      압력  냉각효율 result
0    고장  고부하   정상  35.6  0.577  160.67  39.6     정상
1    고장  저부하   정상  47.5  0.604  158.65  17.6     정상
2    고장  저부하   정상  50.7  0.640  157.76  18.7     정상
3    고장  저부하   정상  51.7  0.635  157.54  19.6     정상
4    고장  저부하   정상  52.4  0.635  157.36  21.1     정상

In [7]:
qc.head()

  검사결과    온도     진동      압력  냉각효율    유량    모터전력  효율지수    보조압력  냉각출력  배유온도
0   합격  44.7  0.615  159.01  35.7  6.66  2465.3  59.7  107.93  1.81  49.7
1   합격  41.9  0.611  159.55  46.3  6.67  2489.1  59.4  108.37  1.87  48.1
2   합격  40.1  0.599  159.87  47.0  6.68  2504.2  59.4  108.61  1.92  46.2
3   합격  38.9  0.587  160.10  47.4  6.67  2513.9  59.1  108.76  1.94  44.9
4   합격  38.0  0.585  160.28  47.3  6.69  2521.8  59.1  108.90  1.97  44.0

In [8]:
qc.info()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   검사결과    200 non-null    str
 1   온도      200 non-null    float64
 2   진동      200 non-null    float64
 3   압력      200 non-null    float64
 4   냉각효율    200 non-null    float64
 5   유량      200 non-null    float64
 6   모터전력    200 non-null    float64
 7   효율지수    200 non-null    float64
 8   보조압력    200 non-null    float64
 9   냉각출력    200 non-null    float64
 10  배유온도    200 non-null    float64
dtypes: float64(10), str(1)
memory usage: 17.3 KB
<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   냉각기상태   120 non-null    str
 1   운전부하    120 non-null    str
 2   밸브상태    120 non-null    str
 3   온도      120 non-null    float64
 4   진동      120 non-null    float64
 5   압력      120 non-null    float64
 6   냉각효율    120 non-null    float64
 7   result  120 non-null    str
dtypes: float64(4), str(4)
memory usage: 7.6 KB

In [9]:
df['냉각기상태'].value_counts()

냉각기상태
고장    40
저하    40
정상    40
Name: count, dtype: int64

In [11]:
df['밸브상태']

0      정상
1      정상
2      정상
3      정상
4      정상
       ..
115    지연
116    정상
117    지연
118    경미
119    정상
Name: 밸브상태, Length: 120, dtype: str

In [12]:
df['밸브상태'].value_counts()

밸브상태
정상    61
지연    20
경미    20
심각    19
Name: count, dtype: int64

In [15]:
df['result'].value_counts(normalize=True).round(3)

result
정상    0.558
고장    0.442
Name: proportion, dtype: float64

In [16]:
pd.set_option('display.precision', 3)

In [17]:
df['result'].value_counts(normalize=True)

result
정상    0.558
고장    0.442
Name: proportion, dtype: float64

In [18]:
df.shape

(120, 8)

In [22]:
df['밸브상태'].value_counts()

밸브상태
정상    61
지연    20
경미    20
심각    19
Name: count, dtype: int64

In [20]:
df['밸브상태'].value_counts(normalize=True)

밸브상태
정상    0.508
지연    0.167
경미    0.167
심각    0.158
Name: proportion, dtype: float64

In [ ]:
#냉각기상태,운전부하,밸브상태,온도,진동,압력,냉각효율,result

In [23]:
df['운전부하'].value_counts(normalize=True)

운전부하
고부하    0.5
저부하    0.5
Name: proportion, dtype: float64

In [24]:
qc.head()

  검사결과    온도     진동      압력  냉각효율    유량    모터전력  효율지수    보조압력  냉각출력  배유온도
0   합격  44.7  0.615  159.01  35.7  6.66  2465.3  59.7  107.93  1.81  49.7
1   합격  41.9  0.611  159.55  46.3  6.67  2489.1  59.4  108.37  1.87  48.1
2   합격  40.1  0.599  159.87  47.0  6.68  2504.2  59.4  108.61  1.92  46.2
3   합격  38.9  0.587  160.10  47.4  6.67  2513.9  59.1  108.76  1.94  44.9
4   합격  38.0  0.585  160.28  47.3  6.69  2521.8  59.1  108.90  1.97  44.0

In [25]:
qc.describe()

,온도,진동,압력,냉각효율,유량,모터전력,효율지수,보조압력,냉각출력,배유온도
count,200.000,200.000,200.000,200.000,200.000,200.000,200.000,200.000,200.000,200.000
mean,37.107,0.564,161.484,45.242,6.528,2543.483,57.551,110.005,1.952,42.641
std,4.847,0.044,2.550,6.544,0.712,26.043,6.055,2.836,0.191,4.401
min,35.300,0.524,156.140,18.800,3.220,2414.700,29.000,105.240,1.070,40.900
25%,35.500,0.547,161.000,46.600,6.680,2539.550,58.800,109.420,1.990,41.100
50%,35.600,0.553,161.030,46.900,6.690,2542.350,58.900,109.575,2.000,41.200
75%,36.200,0.562,161.160,47.200,6.700,2545.000,59.100,109.610,2.010,41.900
max,57.500,0.799,173.320,47.800,6.720,2651.700,59.700,123.100,2.020,60.800

In [26]:
qc.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   검사결과    200 non-null    str
 1   온도      200 non-null    float64
 2   진동      200 non-null    float64
 3   압력      200 non-null    float64
 4   냉각효율    200 non-null    float64
 5   유량      200 non-null    float64
 6   모터전력    200 non-null    float64
 7   효율지수    200 non-null    float64
 8   보조압력    200 non-null    float64
 9   냉각출력    200 non-null    float64
 10  배유온도    200 non-null    float64
dtypes: float64(10), str(1)
memory usage: 17.3 KB

In [27]:
qc['검사결과'].value_counts(normalize=True)

검사결과
합격     0.94
불합격    0.06
Name: proportion, dtype: float64

In [28]:
df['온도']

0      35.6
1      47.5
2      50.7
3      51.7
4      52.4
       ...
115    35.7
116    35.6
117    35.5
118    35.4
119    35.3
Name: 온도, Length: 120, dtype: float64

In [29]:
df['온도'].value_counts()

온도
36.2    8
35.5    7
44.1    6
36.3    5
57.2    4
       ..
45.0    1
44.5    1
36.0    1
35.8    1
35.3    1
Name: count, Length: 62, dtype: int64

In [32]:
print(df['온도'].min())
print(df['온도'].max())

35.3
57.8

In [33]:
df['온도'].value_counts()

온도
36.2    8
35.5    7
44.1    6
36.3    5
57.2    4
       ..
45.0    1
44.5    1
36.0    1
35.8    1
35.3    1
Name: count, Length: 62, dtype: int64

In [34]:
pd.cut(df['온도'],bins=5)

0      (35.277, 39.8]
1        (44.3, 48.8]
2        (48.8, 53.3]
3        (48.8, 53.3]
4        (48.8, 53.3]
            ...
115    (35.277, 39.8]
116    (35.277, 39.8]
117    (35.277, 39.8]
118    (35.277, 39.8]
119    (35.277, 39.8]
Name: 온도, Length: 120, dtype: category
Categories (5, interval[float64, right]): [(35.277, 39.8] < (39.8, 44.3] < (44.3, 48.8] < (48.8, 53.3] < (53.3, 57.8]]

In [35]:
pd.cut(df['온도'],bins=[0,40,50,200])

0        (0, 40]
1       (40, 50]
2      (50, 200]
3      (50, 200]
4      (50, 200]
         ...
115      (0, 40]
116      (0, 40]
117      (0, 40]
118      (0, 40]
119      (0, 40]
Name: 온도, Length: 120, dtype: category
Categories (3, interval[int64, right]): [(0, 40] < (40, 50] < (50, 200]]

In [36]:
pd.cut(df['온도'],
            bins=[0,40,50,200], 
            labels=["Low","Medium","High"])

0         Low
1      Medium
2        High
3        High
4        High
        ...
115       Low
116       Low
117       Low
118       Low
119       Low
Name: 온도, Length: 120, dtype: category
Categories (3, str): ['Low' < 'Medium' < 'High']

In [37]:
band=pd.cut(df['온도'],
            bins=[0,40,50,200], 
            labels=["Low","Medium","High"])

In [38]:
band.value_counts()

온도
Low       41
Medium    40
High      39
Name: count, dtype: int64

In [42]:
df['진동'].head()

0    0.577
1    0.604
2    0.640
3    0.635
4    0.635
Name: 진동, dtype: float64

In [43]:
print(df['진동'].min())
print(df['진동'].max())

0.53
0.779

In [44]:
(0.53 - 0.779) / 3

-0.083

In [46]:
bivra=pd.cut(df['진동'],
            bins=[0.5,0.6,0.7,0.8], 
            labels=["약함","보통","강함"])

In [47]:
bivra.value_counts()

진동
보통    55
약함    48
강함    17
Name: count, dtype: int64

In [48]:
df.groupby('냉각기상태')

In [49]:
print(df.groupby('냉각기상태'))

<pandas.api.typing.DataFrameGroupBy object at 0x000001D2C6721400>

In [51]:
list(df.groupby('냉각기상태'))

[('고장',
     냉각기상태 운전부하 밸브상태    온도     진동      압력  냉각효율 result
  0     고장  고부하   정상  35.6  0.577  160.67  39.6     정상
  1     고장  저부하   정상  47.5  0.604  158.65  17.6     정상
  2     고장  저부하   정상  50.7  0.640  157.76  18.7     정상
  3     고장  저부하   정상  51.7  0.635  157.54  19.6     정상
  4     고장  저부하   정상  52.4  0.635  157.36  21.1     정상
  5     고장  저부하   정상  53.1  0.648  157.20  20.9     정상
  6     고장  저부하   정상  53.5  0.666  157.07  20.1     정상
  7     고장  저부하   정상  53.7  0.656  157.09  19.6     정상
  8     고장  저부하   정상  53.9  0.660  156.95  19.6     정상
  9     고장  저부하   정상  53.9  0.668  157.07  19.6     정상
  10    고장  저부하   정상  54.1  0.667  157.00  20.0     정상
  11    고장  저부하   정상  54.3  0.662  157.01  19.9     정상
  12    고장  저부하   지연  54.2  0.661  156.20  19.9     고장
  13    고장  저부하   경미  54.2  0.648  156.14  19.9     고장
  14    고장  저부하   심각  54.5  0.657  156.54  20.1     고장
  15    고장  저부하   경미  54.4  0.659  156.49  20.0     고장
  16    고장  저부하   심각  54.6  0.666  157.07  20.2     정상
  17    고장  저부하   경미  55.0  0.656  156.79  20.6     정상
  18    고장  저부하   정상  54.5  0.676  156.82  20.4     정상
  19    고장  고부하   심각  54.4  0.749  173.28  20.2     고장
  20    고장  고부하   경미  56.0  0.779  180.41  20.8     고장
  21    고장  고부하   심각  56.6  0.739  180.70  19.7     고장
  22    고장  고부하   경미  56.8  0.733  172.86  19.0     고장
  23    고장  저부하   정상  57.1  0.725  156.08  18.8     정상
  24    고장  저부하   지연  56.3  0.654  156.40  20.3     정상
  25    고장  고부하   정상  56.0  0.733  180.92  20.6     정상
  26    고장  고부하   심각  56.0  0.741  173.03  20.0     고장
  27    고장  고부하   경미  57.1  0.759  173.06  19.3     고장
  28    고장  고부하   심각  57.6  0.719  172.94  18.9     고장
  29    고장  고부하   지연  57.5  0.732  172.87  19.2     고장
  30    고장  고부하   정상  57.8  0.725  172.72  19.2     고장
  31    고장  고부하   지연  57.2  0.774  173.32  19.1     정상
  32    고장  저부하   정상  57.0  0.741  156.60  19.0     정상
  33    고장  고부하   심각  56.3  0.728  173.06  19.6     고장
  34    고장  고부하   지연  57.2  0.706  166.57  18.8     고장
  35    고장  고부하   정상  57.2  0.725  172.58  18.9     고장
  36    고장  고부하   지연  57.2  0.697  166.75  18.8     고장
  37    고장  고부하   정상  57.1  0.719  172.86  18.7     고장
  38    고장  저부하   지연  56.6  0.660  156.31  18.6     정상
  39    고장  저부하   정상  55.9  0.646  156.32  20.1     정상),
 ('저하',
     냉각기상태 운전부하 밸브상태    온도     진동      압력  냉각효율 result
  40    저하  저부하   정상  51.2  0.592  157.09  27.0     정상
  41    저하  저부하   정상  48.1  0.595  157.86  26.3     정상
  42    저하  저부하   정상  47.4  0.596  158.09  26.3     정상
  43    저하  저부하   정상  47.1  0.597  158.16  26.3     정상
  44    저하  저부하   정상  46.9  0.594  158.24  26.2     정상
  45    저하  저부하   정상  46.8  0.593  158.25  26.2     정상
  46    저하  저부하   정상  46.7  0.604  158.30  26.4     정상
  47    저하  저부하   정상  46.6  0.601  158.32  26.3     정상
  48    저하  저부하   정상  46.5  0.614  158.30  26.5     정상
  49    저하  저부하   정상  46.5  0.610  158.35  26.8     정상
  50    저하  저부하   정상  46.4  0.622  158.39  26.5     정상
  51    저하  저부하   심각  46.1  0.617  158.10  26.7     고장
  52    저하  저부하   경미  46.0  0.627  157.92  26.9     고장
  53    저하  저부하   정상  46.0  0.622  157.87  27.2     고장
  54    저하  저부하   지연  45.9  0.629  158.30  27.4     고장
  55    저하  저부하   정상  45.7  0.629  158.24  27.7     고장
  56    저하  저부하   지연  45.7  0.624  158.78  28.2     정상
  57    저하  저부하   정상  45.6  0.611  158.64  28.1     정상
  58    저하  저부하   정상  45.4  0.604  158.65  27.8     정상
  59    저하  저부하   지연  45.0  0.614  158.22  27.8     고장
  60    저하  저부하   정상  44.8  0.614  158.12  27.7     고장
  61    저하  저부하   지연  44.8  0.616  158.55  27.5     고장
  62    저하  저부하   정상  44.6  0.613  158.48  27.8     고장
  63    저하  저부하   심각  44.6  0.609  159.12  27.6     정상
  64    저하  저부하   경미  44.6  0.612  158.96  27.6     정상
  65    저하  저부하   정상  44.4  0.603  158.93  27.6     정상
  66    저하  고부하   지연  44.1  0.623  158.45  27.4     고장
  67    저하  고부하   정상  44.1  0.616  158.38  27.3     고장
  68    저하  저부하   심각  44.1  0.617  158.85  27.9     고장
  69    저하  저부하   경미  44.1  0.613  158.69  27.5     고장
  70    저하  저부하   심각  44.3  0.612  159.23  27.3     정상
  71    저하  저부하   경미  44.3  0.602  159.05  27.4     정상
  72    저하  저부하   정상  44.3  0.604  158.99  27.5     정상
  73    저하  고부하   지연  44.0  0.608  158.52  27.3     고장
  74    저하  저부하   경미  44.0  0.618  158.46  27.7     고장
  75    저하  저부하   심각  44.1  0.606  158.85  27.8     고장
  76    저하  저부하   경미  44.1  0.609  158.69  27.2     고장
  77    저하  저부하   심각  44.4  0.612  159.24  27.5     정상
  78    저하  저부하   경미  44.5  0.607  159.07  27.6     정상
  79    저하  저부하   정상  44.8  0.596  158.96  27.9     정상),
 ('정상',
      냉각기상태 운전부하 밸브상태    온도     진동      압력  냉각효율 result
  80     정상  고부하   정상  36.2  0.563  160.72  47.3     정상
  81     정상  고부하   정상  35.5  0.561  160.97  46.5     정상
  82     정상  고부하   정상  35.4  0.566  161.00  46.6     정상
  83     정상  고부하   정상  35.4  0.561  161.04  46.4     정상
  84     정상  고부하   정상  35.5  0.562  161.01  46.7     정상
  85     정상  고부하   정상  35.5  0.564  161.03  46.7     정상
  86     정상  고부하   정상  35.5  0.561  161.03  46.5     정상
  87     정상  고부하   정상  35.5  0.555  161.04  46.7     정상
  88     정상  고부하   정상  35.4  0.552  161.04  46.9     정상
  89     정상  고부하   정상  35.5  0.557  161.04  47.2     정상
  90     정상  고부하   정상  35.6  0.552  161.16  47.4     정상
  91     정상  고부하   지연  35.7  0.551  160.56  47.2     고장
  92     정상  고부하   경미  35.7  0.539  160.49  47.8     고장
  93     정상  고부하   심각  35.9  0.539  160.91  47.3     고장
  94     정상  고부하   경미  35.9  0.542  160.69  47.4     고장
  95     정상  고부하   심각  36.1  0.551  161.27  47.5     정상
  96     정상  고부하   경미  36.2  0.548  161.08  47.5     정상
  97     정상  고부하   정상  36.3  0.549  161.01  47.3     정상
  98     정상  고부하   심각  36.2  0.547  160.45  47.0     고장
  99     정상  고부하   경미  36.4  0.546  160.22  46.7     고장
  100    정상  고부하   심각  36.4  0.552  160.70  46.3     고장
  101    정상  고부하   경미  36.2  0.550  160.61  46.7     고장
  102    정상  고부하   정상  36.1  0.537  160.96  46.8     정상
  103    정상  고부하   지연  36.2  0.536  161.11  47.2     정상
  104    정상  고부하   정상  36.3  0.530  160.92  47.4     정상
  105    정상  고부하   심각  36.2  0.540  160.48  47.0     고장
  106    정상  고부하   경미  36.3  0.537  160.31  46.8     고장
  107    정상  고부하   정상  36.3  0.541  160.47  46.5     고장
  108    정상  고부하   지연  36.3  0.540  160.64  46.9     고장
  109    정상  고부하   정상  36.2  0.549  160.58  46.8     고장
  110    정상  고부하   지연  36.2  0.544  161.10  47.1     정상
  111    정상  고부하   정상  36.1  0.546  161.00  47.1     정상
  112    정상  고부하   심각  36.0  0.545  160.61  47.5     고장
  113    정상  고부하   지연  35.9  0.550  160.53  46.9     고장
  114    정상  고부하   정상  35.8  0.541  160.41  47.0     고장
  115    정상  고부하   지연  35.7  0.546  160.81  47.0     고장
  116    정상  고부하   정상  35.6  0.544  160.68  46.8     고장
  117    정상  고부하   지연  35.5  0.558  161.32  46.6     정상
  118    정상  고부하   경미  35.4  0.547  161.26  46.6     정상
  119    정상  고부하   정상  35.3  0.547  161.22  46.6     정상)]

In [53]:
list(df.groupby('냉각기상태'))[0]

('고장',
    냉각기상태 운전부하 밸브상태    온도     진동      압력  냉각효율 result
 0     고장  고부하   정상  35.6  0.577  160.67  39.6     정상
 1     고장  저부하   정상  47.5  0.604  158.65  17.6     정상
 2     고장  저부하   정상  50.7  0.640  157.76  18.7     정상
 3     고장  저부하   정상  51.7  0.635  157.54  19.6     정상
 4     고장  저부하   정상  52.4  0.635  157.36  21.1     정상
 5     고장  저부하   정상  53.1  0.648  157.20  20.9     정상
 6     고장  저부하   정상  53.5  0.666  157.07  20.1     정상
 7     고장  저부하   정상  53.7  0.656  157.09  19.6     정상
 8     고장  저부하   정상  53.9  0.660  156.95  19.6     정상
 9     고장  저부하   정상  53.9  0.668  157.07  19.6     정상
 10    고장  저부하   정상  54.1  0.667  157.00  20.0     정상
 11    고장  저부하   정상  54.3  0.662  157.01  19.9     정상
 12    고장  저부하   지연  54.2  0.661  156.20  19.9     고장
 13    고장  저부하   경미  54.2  0.648  156.14  19.9     고장
 14    고장  저부하   심각  54.5  0.657  156.54  20.1     고장
 15    고장  저부하   경미  54.4  0.659  156.49  20.0     고장
 16    고장  저부하   심각  54.6  0.666  157.07  20.2     정상
 17    고장  저부하   경미  55.0  0.656  156.79  20.6     정상
 18    고장  저부하   정상  54.5  0.676  156.82  20.4     정상
 19    고장  고부하   심각  54.4  0.749  173.28  20.2     고장
 20    고장  고부하   경미  56.0  0.779  180.41  20.8     고장
 21    고장  고부하   심각  56.6  0.739  180.70  19.7     고장
 22    고장  고부하   경미  56.8  0.733  172.86  19.0     고장
 23    고장  저부하   정상  57.1  0.725  156.08  18.8     정상
 24    고장  저부하   지연  56.3  0.654  156.40  20.3     정상
 25    고장  고부하   정상  56.0  0.733  180.92  20.6     정상
 26    고장  고부하   심각  56.0  0.741  173.03  20.0     고장
 27    고장  고부하   경미  57.1  0.759  173.06  19.3     고장
 28    고장  고부하   심각  57.6  0.719  172.94  18.9     고장
 29    고장  고부하   지연  57.5  0.732  172.87  19.2     고장
 30    고장  고부하   정상  57.8  0.725  172.72  19.2     고장
 31    고장  고부하   지연  57.2  0.774  173.32  19.1     정상
 32    고장  저부하   정상  57.0  0.741  156.60  19.0     정상
 33    고장  고부하   심각  56.3  0.728  173.06  19.6     고장
 34    고장  고부하   지연  57.2  0.706  166.57  18.8     고장
 35    고장  고부하   정상  57.2  0.725  172.58  18.9     고장
 36    고장  고부하   지연  57.2  0.697  166.75  18.8     고장
 37    고장  고부하   정상  57.1  0.719  172.86  18.7     고장
 38    고장  저부하   지연  56.6  0.660  156.31  18.6     정상
 39    고장  저부하   정상  55.9  0.646  156.32  20.1     정상)

In [54]:
type(list(df.groupby('냉각기상태'))[0])

tuple

In [55]:
(list(df.groupby('냉각기상태'))[0][0])

'고장'

In [56]:
(list(df.groupby('냉각기상태'))[0][1])

   냉각기상태 운전부하 밸브상태    온도     진동      압력  냉각효율 result
0     고장  고부하   정상  35.6  0.577  160.67  39.6     정상
1     고장  저부하   정상  47.5  0.604  158.65  17.6     정상
2     고장  저부하   정상  50.7  0.640  157.76  18.7     정상
3     고장  저부하   정상  51.7  0.635  157.54  19.6     정상
4     고장  저부하   정상  52.4  0.635  157.36  21.1     정상
5     고장  저부하   정상  53.1  0.648  157.20  20.9     정상
6     고장  저부하   정상  53.5  0.666  157.07  20.1     정상
7     고장  저부하   정상  53.7  0.656  157.09  19.6     정상
8     고장  저부하   정상  53.9  0.660  156.95  19.6     정상
9     고장  저부하   정상  53.9  0.668  157.07  19.6     정상
10    고장  저부하   정상  54.1  0.667  157.00  20.0     정상
11    고장  저부하   정상  54.3  0.662  157.01  19.9     정상
12    고장  저부하   지연  54.2  0.661  156.20  19.9     고장
13    고장  저부하   경미  54.2  0.648  156.14  19.9     고장
14    고장  저부하   심각  54.5  0.657  156.54  20.1     고장
15    고장  저부하   경미  54.4  0.659  156.49  20.0     고장
16    고장  저부하   심각  54.6  0.666  157.07  20.2     정상
17    고장  저부하   경미  55.0  0.656  156.79  20.6     정상
18    고장  저부하   정상  54.5  0.676  156.82  20.4     정상
19    고장  고부하   심각  54.4  0.749  173.28  20.2     고장
20    고장  고부하   경미  56.0  0.779  180.41  20.8     고장
21    고장  고부하   심각  56.6  0.739  180.70  19.7     고장
22    고장  고부하   경미  56.8  0.733  172.86  19.0     고장
23    고장  저부하   정상  57.1  0.725  156.08  18.8     정상
24    고장  저부하   지연  56.3  0.654  156.40  20.3     정상
25    고장  고부하   정상  56.0  0.733  180.92  20.6     정상
26    고장  고부하   심각  56.0  0.741  173.03  20.0     고장
27    고장  고부하   경미  57.1  0.759  173.06  19.3     고장
28    고장  고부하   심각  57.6  0.719  172.94  18.9     고장
29    고장  고부하   지연  57.5  0.732  172.87  19.2     고장
30    고장  고부하   정상  57.8  0.725  172.72  19.2     고장
31    고장  고부하   지연  57.2  0.774  173.32  19.1     정상
32    고장  저부하   정상  57.0  0.741  156.60  19.0     정상
33    고장  고부하   심각  56.3  0.728  173.06  19.6     고장
34    고장  고부하   지연  57.2  0.706  166.57  18.8     고장
35    고장  고부하   정상  57.2  0.725  172.58  18.9     고장
36    고장  고부하   지연  57.2  0.697  166.75  18.8     고장
37    고장  고부하   정상  57.1  0.719  172.86  18.7     고장
38    고장  저부하   지연  56.6  0.660  156.31  18.6     정상
39    고장  저부하   정상  55.9  0.646  156.32  20.1     정상

In [58]:
(list(df.groupby('냉각기상태'))[0][1]).describe()

           온도      진동       압력    냉각효율
count  40.000  40.000   40.000  40.000
mean   54.667   0.688  163.676  20.125
std     3.760   0.048    8.638   3.245
min    35.600   0.577  156.080  17.600
25%    54.050   0.656  156.812  19.000
50%    55.450   0.667  157.450  19.650
75%    57.025   0.729  172.863  20.125
max    57.800   0.779  180.920  39.600

In [60]:
(list(df.groupby('냉각기상태'))[1][1])

   냉각기상태 운전부하 밸브상태    온도     진동      압력  냉각효율 result
40    저하  저부하   정상  51.2  0.592  157.09  27.0     정상
41    저하  저부하   정상  48.1  0.595  157.86  26.3     정상
42    저하  저부하   정상  47.4  0.596  158.09  26.3     정상
43    저하  저부하   정상  47.1  0.597  158.16  26.3     정상
44    저하  저부하   정상  46.9  0.594  158.24  26.2     정상
45    저하  저부하   정상  46.8  0.593  158.25  26.2     정상
46    저하  저부하   정상  46.7  0.604  158.30  26.4     정상
47    저하  저부하   정상  46.6  0.601  158.32  26.3     정상
48    저하  저부하   정상  46.5  0.614  158.30  26.5     정상
49    저하  저부하   정상  46.5  0.610  158.35  26.8     정상
50    저하  저부하   정상  46.4  0.622  158.39  26.5     정상
51    저하  저부하   심각  46.1  0.617  158.10  26.7     고장
52    저하  저부하   경미  46.0  0.627  157.92  26.9     고장
53    저하  저부하   정상  46.0  0.622  157.87  27.2     고장
54    저하  저부하   지연  45.9  0.629  158.30  27.4     고장
55    저하  저부하   정상  45.7  0.629  158.24  27.7     고장
56    저하  저부하   지연  45.7  0.624  158.78  28.2     정상
57    저하  저부하   정상  45.6  0.611  158.64  28.1     정상
58    저하  저부하   정상  45.4  0.604  158.65  27.8     정상
59    저하  저부하   지연  45.0  0.614  158.22  27.8     고장
60    저하  저부하   정상  44.8  0.614  158.12  27.7     고장
61    저하  저부하   지연  44.8  0.616  158.55  27.5     고장
62    저하  저부하   정상  44.6  0.613  158.48  27.8     고장
63    저하  저부하   심각  44.6  0.609  159.12  27.6     정상
64    저하  저부하   경미  44.6  0.612  158.96  27.6     정상
65    저하  저부하   정상  44.4  0.603  158.93  27.6     정상
66    저하  고부하   지연  44.1  0.623  158.45  27.4     고장
67    저하  고부하   정상  44.1  0.616  158.38  27.3     고장
68    저하  저부하   심각  44.1  0.617  158.85  27.9     고장
69    저하  저부하   경미  44.1  0.613  158.69  27.5     고장
70    저하  저부하   심각  44.3  0.612  159.23  27.3     정상
71    저하  저부하   경미  44.3  0.602  159.05  27.4     정상
72    저하  저부하   정상  44.3  0.604  158.99  27.5     정상
73    저하  고부하   지연  44.0  0.608  158.52  27.3     고장
74    저하  저부하   경미  44.0  0.618  158.46  27.7     고장
75    저하  저부하   심각  44.1  0.606  158.85  27.8     고장
76    저하  저부하   경미  44.1  0.609  158.69  27.2     고장
77    저하  저부하   심각  44.4  0.612  159.24  27.5     정상
78    저하  저부하   경미  44.5  0.607  159.07  27.6     정상
79    저하  저부하   정상  44.8  0.596  158.96  27.9     정상

In [61]:
df.groupby('냉각기상태')['온도']

In [62]:
list(df.groupby('냉각기상태')['온도'])

[('고장',
  0     35.6
  1     47.5
  2     50.7
  3     51.7
  4     52.4
  5     53.1
  6     53.5
  7     53.7
  8     53.9
  9     53.9
  10    54.1
  11    54.3
  12    54.2
  13    54.2
  14    54.5
  15    54.4
  16    54.6
  17    55.0
  18    54.5
  19    54.4
  20    56.0
  21    56.6
  22    56.8
  23    57.1
  24    56.3
  25    56.0
  26    56.0
  27    57.1
  28    57.6
  29    57.5
  30    57.8
  31    57.2
  32    57.0
  33    56.3
  34    57.2
  35    57.2
  36    57.2
  37    57.1
  38    56.6
  39    55.9
  Name: 온도, dtype: float64),
 ('저하',
  40    51.2
  41    48.1
  42    47.4
  43    47.1
  44    46.9
  45    46.8
  46    46.7
  47    46.6
  48    46.5
  49    46.5
  50    46.4
  51    46.1
  52    46.0
  53    46.0
  54    45.9
  55    45.7
  56    45.7
  57    45.6
  58    45.4
  59    45.0
  60    44.8
  61    44.8
  62    44.6
  63    44.6
  64    44.6
  65    44.4
  66    44.1
  67    44.1
  68    44.1
  69    44.1
  70    44.3
  71    44.3
  72    44.3
  73    44.0
  74    44.0
  75    44.1
  76    44.1
  77    44.4
  78    44.5
  79    44.8
  Name: 온도, dtype: float64),
 ('정상',
  80     36.2
  81     35.5
  82     35.4
  83     35.4
  84     35.5
  85     35.5
  86     35.5
  87     35.5
  88     35.4
  89     35.5
  90     35.6
  91     35.7
  92     35.7
  93     35.9
  94     35.9
  95     36.1
  96     36.2
  97     36.3
  98     36.2
  99     36.4
  100    36.4
  101    36.2
  102    36.1
  103    36.2
  104    36.3
  105    36.2
  106    36.3
  107    36.3
  108    36.3
  109    36.2
  110    36.2
  111    36.1
  112    36.0
  113    35.9
  114    35.8
  115    35.7
  116    35.6
  117    35.5
  118    35.4
  119    35.3
  Name: 온도, dtype: float64)]

In [63]:
(df.groupby('냉각기상태')['온도']).max()

냉각기상태
고장    57.8
저하    51.2
정상    36.4
Name: 온도, dtype: float64

냉각기상태
고장    0.779
저하    0.629
정상    0.566
Name: 진동, dtype: float64

In [69]:
(df.groupby('냉각기상태')['온도']).mean().round(2)

냉각기상태
고장    54.67
저하    45.46
정상    35.89
Name: 온도, dtype: float64

In [67]:
df.groupby('냉각기상태')['온도']).max().round(2)

냉각기상태
고장    57.8
저하    51.2
정상    36.4
Name: 온도, dtype: float64

In [71]:
df.groupby('냉각기상태')['온도'].max().round(2) - df.groupby('냉각기상태')['온도'].mean().round(2)

냉각기상태
고장    3.13
저하    5.74
정상    0.51
Name: 온도, dtype: float64

In [72]:
df.groupby('냉각기상태')['온도'].min().round(2) - df.groupby('냉각기상태')['온도'].mean().round(2)

냉각기상태
고장   -19.07
저하    -1.46
정상    -0.59
Name: 온도, dtype: float64

In [73]:
pd.set_option('display.precision', 2)

In [74]:
#여러기준으로 그룸묶기

In [76]:
df.groupby(['냉각기상태', '운전부하'])

In [77]:
list(df.groupby(['냉각기상태', '운전부하']))

[(('고장', '고부하'),
     냉각기상태 운전부하 밸브상태    온도    진동      압력  냉각효율 result
  0     고장  고부하   정상  35.6  0.58  160.67  39.6     정상
  19    고장  고부하   심각  54.4  0.75  173.28  20.2     고장
  20    고장  고부하   경미  56.0  0.78  180.41  20.8     고장
  21    고장  고부하   심각  56.6  0.74  180.70  19.7     고장
  22    고장  고부하   경미  56.8  0.73  172.86  19.0     고장
  25    고장  고부하   정상  56.0  0.73  180.92  20.6     정상
  26    고장  고부하   심각  56.0  0.74  173.03  20.0     고장
  27    고장  고부하   경미  57.1  0.76  173.06  19.3     고장
  28    고장  고부하   심각  57.6  0.72  172.94  18.9     고장
  29    고장  고부하   지연  57.5  0.73  172.87  19.2     고장
  30    고장  고부하   정상  57.8  0.72  172.72  19.2     고장
  31    고장  고부하   지연  57.2  0.77  173.32  19.1     정상
  33    고장  고부하   심각  56.3  0.73  173.06  19.6     고장
  34    고장  고부하   지연  57.2  0.71  166.57  18.8     고장
  35    고장  고부하   정상  57.2  0.72  172.58  18.9     고장
  36    고장  고부하   지연  57.2  0.70  166.75  18.8     고장
  37    고장  고부하   정상  57.1  0.72  172.86  18.7     고장),
 (('고장', '저부하'),
     냉각기상태 운전부하 밸브상태    온도    진동      압력  냉각효율 result
  1     고장  저부하   정상  47.5  0.60  158.65  17.6     정상
  2     고장  저부하   정상  50.7  0.64  157.76  18.7     정상
  3     고장  저부하   정상  51.7  0.64  157.54  19.6     정상
  4     고장  저부하   정상  52.4  0.64  157.36  21.1     정상
  5     고장  저부하   정상  53.1  0.65  157.20  20.9     정상
  6     고장  저부하   정상  53.5  0.67  157.07  20.1     정상
  7     고장  저부하   정상  53.7  0.66  157.09  19.6     정상
  8     고장  저부하   정상  53.9  0.66  156.95  19.6     정상
  9     고장  저부하   정상  53.9  0.67  157.07  19.6     정상
  10    고장  저부하   정상  54.1  0.67  157.00  20.0     정상
  11    고장  저부하   정상  54.3  0.66  157.01  19.9     정상
  12    고장  저부하   지연  54.2  0.66  156.20  19.9     고장
  13    고장  저부하   경미  54.2  0.65  156.14  19.9     고장
  14    고장  저부하   심각  54.5  0.66  156.54  20.1     고장
  15    고장  저부하   경미  54.4  0.66  156.49  20.0     고장
  16    고장  저부하   심각  54.6  0.67  157.07  20.2     정상
  17    고장  저부하   경미  55.0  0.66  156.79  20.6     정상
  18    고장  저부하   정상  54.5  0.68  156.82  20.4     정상
  23    고장  저부하   정상  57.1  0.72  156.08  18.8     정상
  24    고장  저부하   지연  56.3  0.65  156.40  20.3     정상
  32    고장  저부하   정상  57.0  0.74  156.60  19.0     정상
  38    고장  저부하   지연  56.6  0.66  156.31  18.6     정상
  39    고장  저부하   정상  55.9  0.65  156.32  20.1     정상),
 (('저하', '고부하'),
     냉각기상태 운전부하 밸브상태    온도    진동      압력  냉각효율 result
  66    저하  고부하   지연  44.1  0.62  158.45  27.4     고장
  67    저하  고부하   정상  44.1  0.62  158.38  27.3     고장
  73    저하  고부하   지연  44.0  0.61  158.52  27.3     고장),
 (('저하', '저부하'),
     냉각기상태 운전부하 밸브상태    온도    진동      압력  냉각효율 result
  40    저하  저부하   정상  51.2  0.59  157.09  27.0     정상
  41    저하  저부하   정상  48.1  0.59  157.86  26.3     정상
  42    저하  저부하   정상  47.4  0.60  158.09  26.3     정상
  43    저하  저부하   정상  47.1  0.60  158.16  26.3     정상
  44    저하  저부하   정상  46.9  0.59  158.24  26.2     정상
  45    저하  저부하   정상  46.8  0.59  158.25  26.2     정상
  46    저하  저부하   정상  46.7  0.60  158.30  26.4     정상
  47    저하  저부하   정상  46.6  0.60  158.32  26.3     정상
  48    저하  저부하   정상  46.5  0.61  158.30  26.5     정상
  49    저하  저부하   정상  46.5  0.61  158.35  26.8     정상
  50    저하  저부하   정상  46.4  0.62  158.39  26.5     정상
  51    저하  저부하   심각  46.1  0.62  158.10  26.7     고장
  52    저하  저부하   경미  46.0  0.63  157.92  26.9     고장
  53    저하  저부하   정상  46.0  0.62  157.87  27.2     고장
  54    저하  저부하   지연  45.9  0.63  158.30  27.4     고장
  55    저하  저부하   정상  45.7  0.63  158.24  27.7     고장
  56    저하  저부하   지연  45.7  0.62  158.78  28.2     정상
  57    저하  저부하   정상  45.6  0.61  158.64  28.1     정상
  58    저하  저부하   정상  45.4  0.60  158.65  27.8     정상
  59    저하  저부하   지연  45.0  0.61  158.22  27.8     고장
  60    저하  저부하   정상  44.8  0.61  158.12  27.7     고장
  61    저하  저부하   지연  44.8  0.62  158.55  27.5     고장
  62    저하  저부하   정상  44.6  0.61  158.48  27.8     고장
  63    저하  저부하   심각  44.6  0.61  159.12  27.6     정상
  64    저하  저부하   경미  44.6  0.61  158.96  27.6     정상
  65    저하  저부하   정상  44.4  0.60  158.93  27.6     정상
  68    저하  저부하   심각  44.1  0.62  158.85  27.9     고장
  69    저하  저부하   경미  44.1  0.61  158.69  27.5     고장
  70    저하  저부하   심각  44.3  0.61  159.23  27.3     정상
  71    저하  저부하   경미  44.3  0.60  159.05  27.4     정상
  72    저하  저부하   정상  44.3  0.60  158.99  27.5     정상
  74    저하  저부하   경미  44.0  0.62  158.46  27.7     고장
  75    저하  저부하   심각  44.1  0.61  158.85  27.8     고장
  76    저하  저부하   경미  44.1  0.61  158.69  27.2     고장
  77    저하  저부하   심각  44.4  0.61  159.24  27.5     정상
  78    저하  저부하   경미  44.5  0.61  159.07  27.6     정상
  79    저하  저부하   정상  44.8  0.60  158.96  27.9     정상),
 (('정상', '고부하'),
      냉각기상태 운전부하 밸브상태    온도    진동      압력  냉각효율 result
  80     정상  고부하   정상  36.2  0.56  160.72  47.3     정상
  81     정상  고부하   정상  35.5  0.56  160.97  46.5     정상
  82     정상  고부하   정상  35.4  0.57  161.00  46.6     정상
  83     정상  고부하   정상  35.4  0.56  161.04  46.4     정상
  84     정상  고부하   정상  35.5  0.56  161.01  46.7     정상
  85     정상  고부하   정상  35.5  0.56  161.03  46.7     정상
  86     정상  고부하   정상  35.5  0.56  161.03  46.5     정상
  87     정상  고부하   정상  35.5  0.56  161.04  46.7     정상
  88     정상  고부하   정상  35.4  0.55  161.04  46.9     정상
  89     정상  고부하   정상  35.5  0.56  161.04  47.2     정상
  90     정상  고부하   정상  35.6  0.55  161.16  47.4     정상
  91     정상  고부하   지연  35.7  0.55  160.56  47.2     고장
  92     정상  고부하   경미  35.7  0.54  160.49  47.8     고장
  93     정상  고부하   심각  35.9  0.54  160.91  47.3     고장
  94     정상  고부하   경미  35.9  0.54  160.69  47.4     고장
  95     정상  고부하   심각  36.1  0.55  161.27  47.5     정상
  96     정상  고부하   경미  36.2  0.55  161.08  47.5     정상
  97     정상  고부하   정상  36.3  0.55  161.01  47.3     정상
  98     정상  고부하   심각  36.2  0.55  160.45  47.0     고장
  99     정상  고부하   경미  36.4  0.55  160.22  46.7     고장
  100    정상  고부하   심각  36.4  0.55  160.70  46.3     고장
  101    정상  고부하   경미  36.2  0.55  160.61  46.7     고장
  102    정상  고부하   정상  36.1  0.54  160.96  46.8     정상
  103    정상  고부하   지연  36.2  0.54  161.11  47.2     정상
  104    정상  고부하   정상  36.3  0.53  160.92  47.4     정상
  105    정상  고부하   심각  36.2  0.54  160.48  47.0     고장
  106    정상  고부하   경미  36.3  0.54  160.31  46.8     고장
  107    정상  고부하   정상  36.3  0.54  160.47  46.5     고장
  108    정상  고부하   지연  36.3  0.54  160.64  46.9     고장
  109    정상  고부하   정상  36.2  0.55  160.58  46.8     고장
  110    정상  고부하   지연  36.2  0.54  161.10  47.1     정상
  111    정상  고부하   정상  36.1  0.55  161.00  47.1     정상
  112    정상  고부하   심각  36.0  0.55  160.61  47.5     고장
  113    정상  고부하   지연  35.9  0.55  160.53  46.9     고장
  114    정상  고부하   정상  35.8  0.54  160.41  47.0     고장
  115    정상  고부하   지연  35.7  0.55  160.81  47.0     고장
  116    정상  고부하   정상  35.6  0.54  160.68  46.8     고장
  117    정상  고부하   지연  35.5  0.56  161.32  46.6     정상
  118    정상  고부하   경미  35.4  0.55  161.26  46.6     정상
  119    정상  고부하   정상  35.3  0.55  161.22  46.6     정상)]

In [78]:
list(df.groupby(['냉각기상태', '운전부하']))[0]

(('고장', '고부하'),
    냉각기상태 운전부하 밸브상태    온도    진동      압력  냉각효율 result
 0     고장  고부하   정상  35.6  0.58  160.67  39.6     정상
 19    고장  고부하   심각  54.4  0.75  173.28  20.2     고장
 20    고장  고부하   경미  56.0  0.78  180.41  20.8     고장
 21    고장  고부하   심각  56.6  0.74  180.70  19.7     고장
 22    고장  고부하   경미  56.8  0.73  172.86  19.0     고장
 25    고장  고부하   정상  56.0  0.73  180.92  20.6     정상
 26    고장  고부하   심각  56.0  0.74  173.03  20.0     고장
 27    고장  고부하   경미  57.1  0.76  173.06  19.3     고장
 28    고장  고부하   심각  57.6  0.72  172.94  18.9     고장
 29    고장  고부하   지연  57.5  0.73  172.87  19.2     고장
 30    고장  고부하   정상  57.8  0.72  172.72  19.2     고장
 31    고장  고부하   지연  57.2  0.77  173.32  19.1     정상
 33    고장  고부하   심각  56.3  0.73  173.06  19.6     고장
 34    고장  고부하   지연  57.2  0.71  166.57  18.8     고장
 35    고장  고부하   정상  57.2  0.72  172.58  18.9     고장
 36    고장  고부하   지연  57.2  0.70  166.75  18.8     고장
 37    고장  고부하   정상  57.1  0.72  172.86  18.7     고장)

In [79]:
list(df.groupby(['냉각기상태', '운전부하']))[1]

(('고장', '저부하'),
    냉각기상태 운전부하 밸브상태    온도    진동      압력  냉각효율 result
 1     고장  저부하   정상  47.5  0.60  158.65  17.6     정상
 2     고장  저부하   정상  50.7  0.64  157.76  18.7     정상
 3     고장  저부하   정상  51.7  0.64  157.54  19.6     정상
 4     고장  저부하   정상  52.4  0.64  157.36  21.1     정상
 5     고장  저부하   정상  53.1  0.65  157.20  20.9     정상
 6     고장  저부하   정상  53.5  0.67  157.07  20.1     정상
 7     고장  저부하   정상  53.7  0.66  157.09  19.6     정상
 8     고장  저부하   정상  53.9  0.66  156.95  19.6     정상
 9     고장  저부하   정상  53.9  0.67  157.07  19.6     정상
 10    고장  저부하   정상  54.1  0.67  157.00  20.0     정상
 11    고장  저부하   정상  54.3  0.66  157.01  19.9     정상
 12    고장  저부하   지연  54.2  0.66  156.20  19.9     고장
 13    고장  저부하   경미  54.2  0.65  156.14  19.9     고장
 14    고장  저부하   심각  54.5  0.66  156.54  20.1     고장
 15    고장  저부하   경미  54.4  0.66  156.49  20.0     고장
 16    고장  저부하   심각  54.6  0.67  157.07  20.2     정상
 17    고장  저부하   경미  55.0  0.66  156.79  20.6     정상
 18    고장  저부하   정상  54.5  0.68  156.82  20.4     정상
 23    고장  저부하   정상  57.1  0.72  156.08  18.8     정상
 24    고장  저부하   지연  56.3  0.65  156.40  20.3     정상
 32    고장  저부하   정상  57.0  0.74  156.60  19.0     정상
 38    고장  저부하   지연  56.6  0.66  156.31  18.6     정상
 39    고장  저부하   정상  55.9  0.65  156.32  20.1     정상)

In [86]:
df.groupby(['냉각기상태', '운전부하'])['온도'].mean()

냉각기상태  운전부하
고장     고부하     55.51
       저부하     54.05
저하     고부하     44.07
       저부하     45.58
정상     고부하     35.89
Name: 온도, dtype: float64

In [90]:
pd.groupby([df['냉각기상태'], df['운전부하']])

AttributeError: module 'pandas' has no attribute 'groupby'

In [95]:
pd.crosstab(df["냉각기상태"], df["운전부하"])

운전부하   고부하  저부하
냉각기상태
고장      17   23
저하       3   37
정상      40    0

In [96]:
pd.crosstab(df["밸브상태"], df["result"])

result  고장  정상
밸브상태
경미      14   6
심각      14   5
정상      12  49
지연      13   7

In [97]:
pd.crosstab(df["밸브상태"], df["result"],normalize='columns')

result    고장    정상
밸브상태
경미      0.26  0.09
심각      0.26  0.07
정상      0.23  0.73
지연      0.25  0.10

In [98]:
df.groupby(['냉각기상태', '운전부하'])['온도'].mean()

냉각기상태  운전부하
고장     고부하     55.51
       저부하     54.05
저하     고부하     44.07
       저부하     45.58
정상     고부하     35.89
Name: 온도, dtype: float64

In [99]:
df.groupby(['냉각기상태', '운전부하'])['온도'].mean().unstack()

운전부하     고부하    저부하
냉각기상태
고장     55.51  54.05
저하     44.07  45.58
정상     35.89    NaN

In [100]:
df["밸브상태"] #실습5

0      정상
1      정상
2      정상
3      정상
4      정상
       ..
115    지연
116    정상
117    지연
118    경미
119    정상
Name: 밸브상태, Length: 120, dtype: str

In [102]:
df["밸브상태"].value_counts()

밸브상태
정상    61
지연    20
경미    20
심각    19
Name: count, dtype: int64

In [104]:
df["밸브상태"].shape

(120,)

In [105]:
df["밸브상태"].value_counts()

밸브상태
정상    61
지연    20
경미    20
심각    19
Name: count, dtype: int64

In [103]:
df["밸브상태"].value_counts(normalize=True)

밸브상태
정상    0.51
지연    0.17
경미    0.17
심각    0.16
Name: proportion, dtype: float64

In [122]:
df.groupby(['밸브상태', 'result'])

In [137]:
df.groupby(['밸브상태', 'result']).unstack()

AttributeError: 'DataFrameGroupBy' object has no attribute 'unstack'

In [133]:
list(df.groupby('밸브상태'))[0]

('경미',
     냉각기상태 운전부하 밸브상태    온도    진동      압력  냉각효율 result
 13     고장  저부하   경미  54.2  0.65  156.14  19.9     고장
 15     고장  저부하   경미  54.4  0.66  156.49  20.0     고장
 17     고장  저부하   경미  55.0  0.66  156.79  20.6     정상
 20     고장  고부하   경미  56.0  0.78  180.41  20.8     고장
 22     고장  고부하   경미  56.8  0.73  172.86  19.0     고장
 27     고장  고부하   경미  57.1  0.76  173.06  19.3     고장
 52     저하  저부하   경미  46.0  0.63  157.92  26.9     고장
 64     저하  저부하   경미  44.6  0.61  158.96  27.6     정상
 69     저하  저부하   경미  44.1  0.61  158.69  27.5     고장
 71     저하  저부하   경미  44.3  0.60  159.05  27.4     정상
 74     저하  저부하   경미  44.0  0.62  158.46  27.7     고장
 76     저하  저부하   경미  44.1  0.61  158.69  27.2     고장
 78     저하  저부하   경미  44.5  0.61  159.07  27.6     정상
 92     정상  고부하   경미  35.7  0.54  160.49  47.8     고장
 94     정상  고부하   경미  35.9  0.54  160.69  47.4     고장
 96     정상  고부하   경미  36.2  0.55  161.08  47.5     정상
 99     정상  고부하   경미  36.4  0.55  160.22  46.7     고장
 101    정상  고부하   경미  36.2  0.55  160.61  46.7     고장
 106    정상  고부하   경미  36.3  0.54  160.31  46.8     고장
 118    정상  고부하   경미  35.4  0.55  161.26  46.6     정상)

In [134]:
df = pd.read_csv('C:\\AI Equipment Failure Prediction\\data\\14_hydraulic.csv')

In [135]:
df.head()

  냉각기상태 운전부하 밸브상태    온도    진동      압력  냉각효율 result
0    고장  고부하   정상  35.6  0.58  160.67  39.6     정상
1    고장  저부하   정상  47.5  0.60  158.65  17.6     정상
2    고장  저부하   정상  50.7  0.64  157.76  18.7     정상
3    고장  저부하   정상  51.7  0.64  157.54  19.6     정상
4    고장  저부하   정상  52.4  0.64  157.36  21.1     정상

In [143]:
df.groupby('밸브상태').value_counts()

밸브상태  냉각기상태  운전부하  온도    진동    압력      냉각효율  result
경미    고장     저부하   54.2  0.65  156.14  19.9  고장        1
      정상     고부하   36.2  0.55  161.08  47.5  정상        1
                   35.9  0.54  160.69  47.4  고장        1
      저하     저부하   44.6  0.61  158.96  27.6  정상        1
      고장     고부하   56.8  0.73  172.86  19.0  고장        1
                                                      ..
지연    저하     저부하   45.9  0.63  158.30  27.4  고장        1
                   45.7  0.62  158.78  28.2  정상        1
             고부하   44.1  0.62  158.45  27.4  고장        1
      정상     고부하   36.2  0.54  161.11  47.2  정상        1
      저하     저부하   45.0  0.61  158.22  27.8  고장        1
Name: count, Length: 120, dtype: int64

In [171]:
all=df['밸브상태'].value_counts()

In [150]:
[df['밸브상태'] == '고장']

[0      False
 1      False
 2      False
 3      False
 4      False
        ...
 115    False
 116    False
 117    False
 118    False
 119    False
 Name: 밸브상태, Length: 120, dtype: bool]

In [157]:
error=df[df['result'] == '고장']

In [159]:
error.describe()

          온도     진동      압력   냉각효율
count  53.00  53.00   53.00  53.00
mean   45.70   0.63  162.87  31.38
std     8.47   0.07    6.61  11.76
min    35.60   0.54  156.14  18.70
25%    36.30   0.55  158.46  20.00
50%    44.60   0.62  160.48  27.50
75%    54.50   0.70  166.57  46.80
max    57.80   0.78  180.70  47.80

In [174]:
state=error.groupby('밸브상태').size()

In [161]:
error.groupby('밸브상태').size().sum()

np.int64(53)

In [162]:
print(error.groupby('밸브상태').size().sum())

53

In [175]:
percentage = (state/all).round(3)

In [176]:
print(percentage.sort_values(ascending=False))

밸브상태
심각    0.74
경미    0.70
지연    0.65
정상    0.20
dtype: float64

In [177]:
#14-2 pdf

In [182]:
print(df.groupby('냉각기상태')['온도'].agg(['mean', 'std', 'max','min']))

        mean   std   max   min
냉각기상태
고장     54.67  3.76  57.8  35.6
저하     45.46  1.47  51.2  44.0
정상     35.89  0.36  36.4  35.3

In [186]:
summary = df.groupby('냉각기상태').agg(
    평균온도=('온도', 'mean'),
    온도편차=('온도', 'std'),
    평균진동=('진동', 'mean'),
    측정수=('온도', 'count'),
).round(2)

In [187]:
print(summary)

        평균온도  온도편차  평균진동  측정수
냉각기상태
고장     54.67  3.76  0.69   40
저하     45.46  1.47  0.61   40
정상     35.89  0.36  0.55   40

In [191]:
qc['검사결과']

0       합격
1       합격
2       합격
3       합격
4       합격
      ...
195    불합격
196    불합격
197    불합격
198    불합격
199    불합격
Name: 검사결과, Length: 200, dtype: str

In [192]:
print(qc.groupby('검사결과')['온도'].agg(['mean', 'std', 'max','min']))

       mean   std   max   min
검사결과
불합격   55.84  1.32  57.5  54.2
합격    35.91  0.97  44.7  35.3

In [196]:
summary2 = qc.groupby('검사결과').agg(
    평균온도=('온도', 'mean'),
    평균냉각효율=('냉각효율', 'mean'),
    측정수=('온도', 'count')
)

In [197]:
print(summary2).__annotations__

       평균온도  평균냉각효율  측정수
검사결과
불합격   55.84   19.65   12
합격    35.91   46.88  188

In [199]:
df.groupby('냉각기상태')['온도'].transform('mean').round(2)

0      54.67
1      54.67
2      54.67
3      54.67
4      54.67
       ...
115    35.89
116    35.89
117    35.89
118    35.89
119    35.89
Name: 온도, Length: 120, dtype: float64

In [200]:
marked=df.copy()

In [204]:
marked.head()

  냉각기상태 운전부하 밸브상태    온도    진동      압력  냉각효율 result   그룹평균
0    고장  고부하   정상  35.6  0.58  160.67  39.6     정상  54.67
1    고장  저부하   정상  47.5  0.60  158.65  17.6     정상  54.67
2    고장  저부하   정상  50.7  0.64  157.76  18.7     정상  54.67
3    고장  저부하   정상  51.7  0.64  157.54  19.6     정상  54.67
4    고장  저부하   정상  52.4  0.64  157.36  21.1     정상  54.67

In [202]:
marked['그룹평균'] = marked.groupby('냉각기상태')['온도'].transform('mean').round(2)

In [ ]:
marked['편차'] = marked['온도'] - marked['그룹평균']

In [205]:
marked['온도'] - marked['그룹평균']

0     -19.07
1      -7.17
2      -3.97
3      -2.97
4      -2.27
       ...
115    -0.19
116    -0.29
117    -0.39
118    -0.49
119    -0.59
Length: 120, dtype: float64

In [206]:
marked['편차'] = marked['온도'] - marked['그룹평균']

In [209]:
marked.head()

  냉각기상태 운전부하 밸브상태    온도    진동      압력  냉각효율 result   그룹평균     편차
0    고장  고부하   정상  35.6  0.58  160.67  39.6     정상  54.67 -19.07
1    고장  저부하   정상  47.5  0.60  158.65  17.6     정상  54.67  -7.17
2    고장  저부하   정상  50.7  0.64  157.76  18.7     정상  54.67  -3.97
3    고장  저부하   정상  51.7  0.64  157.54  19.6     정상  54.67  -2.97
4    고장  저부하   정상  52.4  0.64  157.36  21.1     정상  54.67  -2.27

In [212]:
marked.groupby('냉각기상태')['편차'].sum().round(2)

냉각기상태
고장   -0.1
저하    0.2
정상   -0.2
Name: 편차, dtype: float64

In [215]:
pd.pivot_table(df, index='밸브상태', columns='운전부하',
values='온도', aggfunc='mean',margins=True).round(2)

운전부하    고부하    저부하    All
밸브상태
경미    42.20  47.52  44.86
심각    45.25  47.09  46.02
정상    39.34  49.40  45.11
지연    43.75  49.79  45.86
All   41.85  48.82  45.34

In [216]:
df.head()

  냉각기상태 운전부하 밸브상태    온도    진동      압력  냉각효율 result
0    고장  고부하   정상  35.6  0.58  160.67  39.6     정상
1    고장  저부하   정상  47.5  0.60  158.65  17.6     정상
2    고장  저부하   정상  50.7  0.64  157.76  18.7     정상
3    고장  저부하   정상  51.7  0.64  157.54  19.6     정상
4    고장  저부하   정상  52.4  0.64  157.36  21.1     정상

In [ ]:
dfc=df.copy() #실습2

In [218]:
dfc['온도평균'] = marked.groupby('냉각기상태')['온도'].transform('mean').round(2)

In [220]:
dfc.head()

  냉각기상태 운전부하 밸브상태    온도    진동      압력  냉각효율 result   온도평균
0    고장  고부하   정상  35.6  0.58  160.67  39.6     정상  54.67
1    고장  저부하   정상  47.5  0.60  158.65  17.6     정상  54.67
2    고장  저부하   정상  50.7  0.64  157.76  18.7     정상  54.67
3    고장  저부하   정상  51.7  0.64  157.54  19.6     정상  54.67
4    고장  저부하   정상  52.4  0.64  157.36  21.1     정상  54.67

In [221]:
dfc['편차'] = dfc['온도'] - dfc['온도평균']

In [223]:
dfc.head(3)

  냉각기상태 운전부하 밸브상태    온도    진동      압력  냉각효율 result   온도평균     편차
0    고장  고부하   정상  35.6  0.58  160.67  39.6     정상  54.67 -19.07
1    고장  저부하   정상  47.5  0.60  158.65  17.6     정상  54.67  -7.17
2    고장  저부하   정상  50.7  0.64  157.76  18.7     정상  54.67  -3.97

In [225]:
print(dfc['편차'].max())
print(dfc['편차'].min())

5.740000000000002
-19.07

In [ ]:
print(dfc['편차'].max())
print(dfc['편차'].min())

In [226]:
pd.pivot_table(dfc, index='밸브상태', columns='운전부하',
values='온도', aggfunc='mean',margins=True).round(2)

운전부하    고부하    저부하    All
밸브상태
경미    42.20  47.52  44.86
심각    45.25  47.09  46.02
정상    39.34  49.40  45.11
지연    43.75  49.79  45.86
All   41.85  48.82  45.34

In [228]:
print(round(df['온도'].corr(df['진동']), 3))
print(round(df['온도'].corr(df['압력']), 3))
print(round(df['온도'].corr(df['냉각효율']), 3))

0.931
0.284
-0.951

In [231]:
df[['온도', '진동', '압력', '냉각효율']].corr()

        온도    진동    압력  냉각효율
온도    1.00  0.93  0.28 -0.95
진동    0.93  1.00  0.52 -0.86
압력    0.28  0.52  1.00 -0.13
냉각효율 -0.95 -0.86 -0.13  1.00

In [232]:
#압력 냉각효율은 상관 관계가 약하다
#온도 진동 은 상관관계가 강하다

In [233]:
qcc=qc.copy()

In [234]:
#실습4

In [235]:
sensor_cals = [c for c in qcc.columns if c != '검사결과']

In [236]:
sensor_cals

['온도', '진동', '압력', '냉각효율', '유량', '모터전력', '효율지수', '보조압력', '냉각출력', '배유온도']

In [237]:
sensors = qcc.drop(columns='검사결과')

In [238]:
sensors

       온도    진동      압력  냉각효율    유량    모터전력  효율지수    보조압력  냉각출력  배유온도
0    44.7  0.61  159.01  35.7  6.66  2465.3  59.7  107.93  1.81  49.7
1    41.9  0.61  159.55  46.3  6.67  2489.1  59.4  108.37  1.87  48.1
2    40.1  0.60  159.87  47.0  6.68  2504.2  59.4  108.61  1.92  46.2
3    38.9  0.59  160.10  47.4  6.67  2513.9  59.1  108.76  1.94  44.9
4    38.0  0.58  160.28  47.3  6.69  2521.8  59.1  108.90  1.97  44.0
..    ...   ...     ...   ...   ...     ...   ...     ...   ...   ...
195  57.0  0.73  172.68  18.8  3.29  2633.0  30.3  122.84  1.08  60.6
196  57.5  0.71  172.51  18.9  3.29  2626.9  30.4  122.94  1.07  60.8
197  56.6  0.74  172.92  18.9  3.22  2626.6  29.1  122.47  1.09  59.9
198  57.1  0.80  172.78  19.0  3.29  2624.0  29.5  122.56  1.11  60.4
199  57.2  0.73  172.56  18.9  3.26  2621.5  30.2  122.95  1.10  60.7

[200 rows x 10 columns]

In [242]:
type(sensors)

pandas.DataFrame

In [244]:
sensor_cols = [c for c in qcc.columns if c != '검사결과']

In [246]:
print   (sensor_cols)

['온도', '진동', '압력', '냉각효율', '유량', '모터전력', '효율지수', '보조압력', '냉각출력', '배유온도']

In [247]:
sensor_cols = qcc.columns.drop('검사결과').tolist()

In [249]:
corr_matrix = qc[sensor_cols].corr()

In [250]:
print(corr_matrix.shape)

(10, 10)

In [251]:
pairs = corr_matrix.unstack()
print(len(pairs))

100

In [252]:
pairs.head

<bound method NDFrame.head of 온도    온도      1.00
      진동      0.94
      압력      0.72
      냉각효율   -0.98
      유량     -0.90
              ...
배유온도  모터전력    0.30
      효율지수   -0.87
      보조압력    0.74
      냉각출력   -0.95
      배유온도    1.00
Length: 100, dtype: float64>

In [253]:
upper = pairs[[a < b for a, b in pairs.index]]

In [254]:
print(len(upper))

45

In [255]:
print(int((upper.abs() >= 0.4).sum())) # 42
print(int((upper.abs() >= 0.95).sum())) # 14

42
14

In [256]:
print(upper.abs().sort_values(ascending=False).head(5).round(3).to_dict())

{('배유온도', '온도'): 0.999, ('유량', '효율지수'): 0.999, ('보조압력', '압력'): 0.993, ('냉각효율', '온도'): 0.983, ('냉각출력', '유량'): 0.982}

In [ ]:
#실습5
cycle = pd.read_csv('C:\\AI Equipment Failure Prediction\\data/14_hydraulic.csv')
spec = pd.read_csv('C:\\AI Equipment Failure Prediction\\data/14_hydraulic_std.csv')

In [270]:
cycle.head(5)

  냉각기상태 운전부하 밸브상태    온도    진동      압력  냉각효율 result
0    고장  고부하   정상  35.6  0.58  160.67  39.6     정상
1    고장  저부하   정상  47.5  0.60  158.65  17.6     정상
2    고장  저부하   정상  50.7  0.64  157.76  18.7     정상
3    고장  저부하   정상  51.7  0.64  157.54  19.6     정상
4    고장  저부하   정상  52.4  0.64  157.36  21.1     정상

In [271]:
spec.head(5)

  냉각기상태         상태설명  권장점검주기   담당팀  위험도
0    정상     냉각 성능 정상     180  보전1팀    1
1    저하     냉각 성능 저하      60  보전1팀    2
2    고장  냉각 성능 상실 근접       7  보전2팀    3
3   점검중      정비 입고 중       0  보전2팀    0

In [259]:
print(cycle.shape, spec.shape)

(120, 8) (4, 5)

In [268]:
print([c for c in cycle.columns if c in spec.columns])

['냉각기상태']

In [261]:
joined = cycle.merge(spec, on=['냉각기상태'], how='left')

In [ ]:
joined.head(5) #확인

,냉각기상태,운전부하,밸브상태,온도,진동,압력,냉각효율,result,상태설명,권장점검주기,담당팀,위험도
0,고장,고부하,정상,35.6,0.58,160.67,39.6,정상,냉각 성능 상실 근접,7,보전2팀,3
1,고장,저부하,정상,47.5,0.60,158.65,17.6,정상,냉각 성능 상실 근접,7,보전2팀,3
2,고장,저부하,정상,50.7,0.64,157.76,18.7,정상,냉각 성능 상실 근접,7,보전2팀,3
3,고장,저부하,정상,51.7,0.64,157.54,19.6,정상,냉각 성능 상실 근접,7,보전2팀,3
4,고장,저부하,정상,52.4,0.64,157.36,21.1,정상,냉각 성능 상실 근접,7,보전2팀,3

In [273]:
joined.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   냉각기상태   120 non-null    str
 1   운전부하    120 non-null    str
 2   밸브상태    120 non-null    str
 3   온도      120 non-null    float64
 4   진동      120 non-null    float64
 5   압력      120 non-null    float64
 6   냉각효율    120 non-null    float64
 7   result  120 non-null    str
 8   상태설명    120 non-null    str
 9   권장점검주기  120 non-null    int64
 10  담당팀     120 non-null    str
 11  위험도     120 non-null    int64
dtypes: float64(4), int64(2), str(6)
memory usage: 11.4 KB

In [274]:
print(joined['온도'].max())
print(joined['온도'].min())

57.8
35.3

In [286]:
temp_cut=pd.cut(joined['온도'],
            bins=[0,40,50,200], 
            labels=["낮","중","높"])

In [287]:
temp_cut.value_counts()

온도
낮    41
중    40
높    39
Name: count, dtype: int64

In [301]:
temp_cut=pd.cut(joined['온도'],  #3
            bins=[0,40,50,200], 
            labels=["낮음","중간","높음"])
joined['온도_구간'] = temp_cut

In [305]:
summary = temp_cut.groupby(['냉각기상태']).agg(                    #4
    건수=('온도', 'count'),
    평균온도=('온도', 'mean'),
    흩어짐=('온도', 'std'), #?
).round(2)

KeyError: '냉각기상태'

In [311]:
joined.head()

,냉각기상태,운전부하,밸브상태,온도,진동,압력,냉각효율,result,상태설명,권장점검주기,담당팀,위험도,온도_구간
0,고장,고부하,정상,35.6,0.58,160.67,39.6,정상,냉각 성능 상실 근접,7,보전2팀,3,낮음
1,고장,저부하,정상,47.5,0.60,158.65,17.6,정상,냉각 성능 상실 근접,7,보전2팀,3,중간
2,고장,저부하,정상,50.7,0.64,157.76,18.7,정상,냉각 성능 상실 근접,7,보전2팀,3,높음
3,고장,저부하,정상,51.7,0.64,157.54,19.6,정상,냉각 성능 상실 근접,7,보전2팀,3,높음
4,고장,저부하,정상,52.4,0.64,157.36,21.1,정상,냉각 성능 상실 근접,7,보전2팀,3,높음

In [312]:
joined.columns

Index(['냉각기상태', '운전부하', '밸브상태', '온도', '진동', '압력', '냉각효율', 'result', '상태설명',
       '권장점검주기', '담당팀', '위험도', '온도_구간'],
      dtype='str')

In [329]:
summary = joined.groupby('냉각기상태').agg(                    #4
    측정수=('온도', 'count'), 
    평균온도=('온도', 'mean'),
    온도편차=('온도', 'std'),
    위험도=('위험도', 'max'),
    평균냉각효율=('냉각효율', 'mean'), 
    점검주기=('권장점검주기', 'max'),

).round(2)

In [330]:
summary

       측정수   평균온도  온도편차  위험도  평균냉각효율  점검주기
냉각기상태
고장      40  54.67  3.76    3   20.12     7
저하      40  45.46  1.47    2   27.24    60
정상      40  35.89  0.36    1   46.96   180

In [331]:
print(pd.crosstab(joined["냉각기상태"], joined["온도_구간"])) #5

온도_구간  낮음  중간  높음
냉각기상태
고장      1   1  38
저하      0  39   1
정상     40   0   0

In [332]:
print(round(df['온도'].corr(df['냉각효율']), 3)) #6
print(round(df['온도'].corr(df['진동']), 3))

-0.951
0.931

In [333]:
print(summary.sort_values(['위험도', '평균온도'],ascending=[False, False]))

       측정수   평균온도  온도편차  위험도  평균냉각효율  점검주기
냉각기상태
고장      40  54.67  3.76    3   20.12     7
저하      40  45.46  1.47    2   27.24    60
정상      40  35.89  0.36    1   46.96   180

In [ ]:
#분산을 봣을때 온도와 냉각효율 온도와 진동이 상관관계가 이;ㅅ다
#문제를 잘못낸거같다. 질문이 틀렷다 !