In [2]:
print("Hello, world!")

Hello, world!

In [3]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('c:/ex/data/13_diecasting_shot.csv')

In [ ]:
df.head()

   샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
0  1  DIE-A-01  214.0  1037.0   20.7   10.0  258.0   양품
1  2  DIE-B-01  217.0  1052.0   20.7   11.0  257.0   양품
2  3  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
3  4  DIE-B-02  217.0  1052.0   20.6   11.0  253.0   양품
4  5  DIE-A-01  217.0  1052.0   20.6   11.0  254.0   양품

In [ ]:
df['비스킷두께']

0      10.0
1      11.0
2      11.0
3      11.0
4      11.0
       ...
195    19.0
196    20.0
197    27.0
198    19.0
199    15.0
Name: 비스킷두께, Length: 200, dtype: float64

In [ ]:
df['비스킷두께'] >16

0      False
1      False
2      False
3      False
4      False
       ...
195     True
196     True
197     True
198     True
199    False
Name: 비스킷두께, Length: 200, dtype: bool

In [ ]:
cond=df['비스킷두께']>16

In [ ]:
print(cond.head(3).tolist())

[False, False, False]

In [ ]:
cond.sum()

np.int64(65)

In [ ]:
df[cond]

       샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
42    43  DIE-A-01  215.0  1040.0   20.7   21.0  253.0   주의
67    68  DIE-B-02  215.0  1040.0   21.1   17.0  257.0   양품
108  109  DIE-A-01  264.0   594.0   36.4   18.0  363.0   양품
109  110  DIE-A-02  265.0   596.0   36.6   17.0  352.0   양품
110  111  DIE-A-02  264.0   595.0   37.0   18.0  361.0   양품
..   ...       ...    ...     ...    ...    ...    ...  ...
194  195  DIE-A-02  260.0   585.0   33.9   19.0  348.0   불량
195  196  DIE-A-01  264.0   594.0   76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0   595.0   36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0   255.0   36.6   27.0  354.0   불량
198  199  DIE-B-02  264.0   595.0   36.1   19.0  372.0   불량

[65 rows x 8 columns]

In [ ]:
df[cond]['비스킷두께']

42     21.0
67     17.0
108    18.0
109    17.0
110    18.0
       ...
194    19.0
195    19.0
196    20.0
197    27.0
198    19.0
Name: 비스킷두께, Length: 65, dtype: float64

In [ ]:
df[cond]['비스킷두께'].isna().sum()

np.int64(0)

In [ ]:
df = pd.read_csv('c:/ex/data/13_diecasting_shot.csv')

In [ ]:
print(len(df))

200

In [ ]:
df = pd.read_csv('C:/ex/data/13_diecasting_shot.csv')

In [ ]:
cond=df['비스킷두께']>=16
print(cond.sum())

74

In [ ]:
lowcond=df['비스킷두께']<16
print(lowcond.sum())

112

In [ ]:
print(lowcond.sum()+cond.sum())

186

In [ ]:
wtff=print(df['비스킷두께'].isna().sum())

14

In [ ]:
both = df[(df['비스킷두께']>=16) & (df['사이클타임']>=25)]
either = df[(df['비스킷두께']>=16) | (df['사이클타임']>=25)]

print(len(both), len(either))

72 86

In [ ]:
(df['비스킷두께']>=16) & (df['사이클타임']>=25)

0      False
1      False
2      False
3      False
4      False
       ...
195     True
196     True
197     True
198     True
199    False
Length: 200, dtype: bool

In [ ]:
#~

In [ ]:
~5

-6

In [ ]:
type()

SyntaxError: invalid syntax (101215362.py, line 1)

In [ ]:
~5+1

-5

In [ ]:
df['품질등급']

0      양품
1      양품
2      양품
3      양품
4      양품
       ..
195    불량
196    불량
197    불량
198    불량
199    불량
Name: 품질등급, Length: 200, dtype: str

In [ ]:
df['품질등급'] == '불량'

0      False
1      False
2      False
3      False
4      False
       ...
195     True
196     True
197     True
198     True
199     True
Name: 품질등급, Length: 200, dtype: bool

In [ ]:
df[df['품질등급'] == '불량']

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
180  181  DIE-B-01  108.0   522.0   652.3   14.0  222.0   불량
181  182  DIE-C-01  214.0  1036.0    93.1   12.0  247.0   불량
182  183  DIE-A-02  215.0  1041.0    21.3    4.0  258.0   불량
183  184  DIE-B-01  216.0  1044.0    21.2   11.0  259.0   불량
184  185  DIE-B-01  219.0  1058.0    21.3    2.0  255.0   불량
185  186  DIE-B-02  218.0  1054.0    21.4    2.0  253.0   불량
186  187  DIE-C-01  108.0   524.0    22.9   14.0  247.0   불량
187  188  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량
188  189  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량
189  190  DIE-B-01    NaN     NaN     NaN    NaN    NaN   불량
190  191  DIE-B-02  238.0  1152.0    91.2   13.0  254.0   불량
191  192  DIE-B-01  113.0   255.0    36.9   26.0  366.0   불량
192  193  DIE-A-02  264.0   594.0    36.9   19.0  355.0   불량
193  194  DIE-C-01  113.0   255.0    34.4   19.0  370.0   불량
194  195  DIE-A-02  260.0   585.0    33.9   19.0  348.0   불량
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량
198  199  DIE-B-02  264.0   595.0    36.1   19.0  372.0   불량
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량

In [ ]:
len(df[df['품질등급'] == '불량'])

20

In [ ]:
len(df[~(df['품질등급'] == '불량')])

180

In [ ]:
df = pd.read_csv('c:/ex/data/13_diecasting_shot.csv')

In [ ]:
df.shape

(200, 8)

In [ ]:
bisket = df['비스킷두께']>=16
sicle = df['사이클타임']>=25

In [ ]:
print(len(df[bisket & sicle]))
print(len(df[bisket | sicle]))

72
86

In [ ]:
print(len(df[(df['bisket']>=16) & (df['설설설설설 ']>=25)]))  # 72

In [ ]:
df['품질등급'].isin(['주의'])

0      False
1      False
2      False
3      False
4      False
       ...
195    False
196    False
197    False
198    False
199    False
Name: 품질등급, Length: 200, dtype: bool

In [ ]:
print(df['품질등급'].isin(['주의']).sum())

18

In [ ]:
df['품질등급'].isna().sum()

np.int64(0)

In [ ]:
len(df[df['품질등급'].isin(['주의'])])

18

In [ ]:
df[df['품질등급'].isin(['주의'])]

       샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
42    43  DIE-A-01  215.0  1040.0   20.7   21.0  253.0   주의
89    90  DIE-A-02  235.0  1137.0   22.5    7.0  255.0   주의
120  121  DIE-A-01  265.0   596.0   33.9   19.0  354.0   주의
122  123  DIE-C-01  265.0   596.0   33.7   19.0  357.0   주의
123  124  DIE-B-02  265.0   595.0   33.9   19.0  359.0   주의
124  125  DIE-A-01  265.0   595.0   33.8   19.0  355.0   주의
132  133  DIE-A-01  265.0   596.0   35.0   19.0  373.0   주의
135  136  DIE-A-02  265.0   595.0   36.0   19.0  377.0   주의
146  147  DIE-A-02  263.0   592.0  125.9   19.0  372.0   주의
148  149  DIE-B-02  265.0   596.0   36.0   19.0  377.0   주의
149  150  DIE-A-01  265.0   596.0   36.1   19.0  350.0   주의
151  152  DIE-A-01  265.0   595.0   35.9   19.0  381.0   주의
152  153  DIE-A-02  265.0   595.0   36.0   19.0  352.0   주의
154  155  DIE-A-01  265.0   595.0   35.8   19.0  363.0   주의
155  156  DIE-A-01  265.0   596.0   35.7   19.0  364.0   주의
163  164  DIE-B-02  265.0   595.0   35.8   19.0  379.0   주의
167  168  DIE-A-01  265.0   596.0   36.0   19.0  379.0   주의
170  171  DIE-B-02  265.0   596.0   36.1   20.0  370.0   주의

In [ ]:
df['비스킷두께'].between(10, 16)

0       True
1       True
2       True
3       True
4       True
       ...
195    False
196    False
197    False
198    False
199     True
Name: 비스킷두께, Length: 200, dtype: bool

In [ ]:
len(df[df['비스킷두께'].between(10, 16)])

117

In [ ]:
len(df[df['비스킷두께'].isna()])

14

In [ ]:
len(df[~df['비스킷두께'].isna()])

186

In [ ]:
df[df['설비ID'].str.contains('A')]

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
0      1  DIE-A-01  214.0  1037.0    20.7   10.0  258.0   양품
4      5  DIE-A-01  217.0  1052.0    20.6   11.0  254.0   양품
5      6  DIE-A-01  217.0  1052.0    20.6   11.0  257.0   양품
6      7  DIE-A-01  215.0  1038.0    20.9   11.0  250.0   양품
7      8  DIE-A-01  215.0  1038.0    20.9   11.0  258.0   양품
..   ...       ...    ...     ...     ...    ...    ...  ...
194  195  DIE-A-02  260.0   585.0    33.9   19.0  348.0   불량
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량

[111 rows x 8 columns]

In [ ]:
spllllll=df['설비ID'].str.split('-')    
spllllll.head()

0    [DIE, A, 01]
1    [DIE, B, 01]
2    [DIE, B, 01]
3    [DIE, B, 02]
4    [DIE, A, 01]
Name: 설비ID, dtype: object

In [ ]:
spllllll.values

array([list(['DIE', 'A', '01']), list(['DIE', 'B', '01']),
       list(['DIE', 'B', '01']), list(['DIE', 'B', '02']),
       list(['DIE', 'A', '01']), list(['DIE', 'A', '01']),
       list(['DIE', 'A', '01']), list(['DIE', 'A', '01']),
       list(['DIE', 'B', '02']), list(['DIE', 'A', '01']),
       list(['DIE', 'B', '01']), list(['DIE', 'A', '01']),
       list(['DIE', 'A', '02']), list(['DIE', 'A', '02']),
       list(['DIE', 'B', '02']), list(['DIE', 'B', '01']),
       list(['DIE', 'A', '01']), list(['DIE', 'A', '02']),
       list(['DIE', 'A', '01']), list(['DIE', 'B', '02']),
       list(['DIE', 'B', '02']), list(['DIE', 'B', '02']),
       list(['DIE', 'B', '02']), list(['DIE', 'B', '02']),
       list(['DIE', 'C', '01']), list(['DIE', 'B', '02']),
       list(['DIE', 'A', '01']), list(['DIE', 'B', '02']),
       list(['DIE', 'A', '02']), list(['DIE', 'B', '02']),
       list(['DIE', 'B', '01']), list(['DIE', 'A', '02']),
       list(['DIE', 'A', '02']), list(['DIE', 'A', '02']),
       list(['DIE', 'A', '02']), list(['DIE', 'A', '01']),
       list(['DIE', 'B', '02']), list(['DIE', 'B', '02']),
       list(['DIE', 'C', '01']), list(['DIE', 'B', '01']),
       list(['DIE', 'B', '01']), list(['DIE', 'B', '02']),
       list(['DIE', 'A', '01']), list(['DIE', 'B', '01']),
       list(['DIE', 'A', '02']), list(['DIE', 'A', '01']),
       list(['DIE', 'A', '01']), list(['DIE', 'B', '01']),
       list(['DIE', 'A', '01']), list(['DIE', 'A', '02']),
       list(['DIE', 'B', '01']), list(['DIE', 'A', '02']),
       list(['DIE', 'A', '01']), list(['DIE', 'A', '02']),
       list(['DIE', 'A', '01']), list(['DIE', 'A', '01']),
       list(['DIE', 'A', '01']), list(['DIE', 'A', '02']),
       list(['DIE', 'A', '01']), list(['DIE', 'B', '01']),
       list(['DIE', 'C', '01']), list(['DIE', 'A', '02']),
       list(['DIE', 'B', '02']), list(['DIE', 'C', '01']),
       list(['DIE', 'A', '01']), list(['DIE', 'A', '01']),
       list(['DIE', 'B', '02']), list(['DIE', 'B', '02']),
       list(['DIE', 'B', '01']), list(['DIE', 'A', '01']),
       list(['DIE', 'A', '02']), list(['DIE', 'B', '02']),
       list(['DIE', 'C', '01']), list(['DIE', 'B', '02']),
       list(['DIE', 'A', '01']), list(['DIE', 'B', '02']),
       list(['DIE', 'A', '02']), list(['DIE', 'B', '02']),
       list(['DIE', 'A', '01']), list(['DIE', 'C', '01']),
       list(['DIE', 'B', '01']), list(['DIE', 'B', '02']),
       list(['DIE', 'A', '01']), list(['DIE', 'B', '01']),
       list(['DIE', 'B', '01']), list(['DIE', 'B', '01']),
       list(['DIE', 'A', '02']), list(['DIE', 'B', '02']),
       list(['DIE', 'A', '02']), list(['DIE', 'A', '02']),
       list(['DIE', 'A', '01']), list(['DIE', 'B', '01']),
       list(['DIE', 'A', '01']), list(['DIE', 'A', '01']),
       list(['DIE', 'A', '01']), list(['DIE', 'B', '01']),
       list(['DIE', 'B', '01']), list(['DIE', 'B', '01']),
       list(['DIE', 'A', '01']), list(['DIE', 'A', '02']),
       list(['DIE', 'A', '02']), list(['DIE', 'A', '01']),
       list(['DIE', 'A', '01']), list(['DIE', 'C', '01']),
       list(['DIE', 'A', '01']), list(['DIE', 'A', '02']),
       list(['DIE', 'A', '02']), list(['DIE', 'B', '01']),
       list(['DIE', 'A', '01']), list(['DIE', 'A', '02']),
       list(['DIE', 'A', '02']), list(['DIE', 'B', '02']),
       list(['DIE', 'A', '01']), list(['DIE', 'A', '02']),
       list(['DIE', 'A', '02']), list(['DIE', 'C', '01']),
       list(['DIE', 'B', '01']), list(['DIE', 'A', '02']),
       list(['DIE', 'B', '01']), list(['DIE', 'A', '02']),
       list(['DIE', 'A', '01']), list(['DIE', 'B', '01']),
       list(['DIE', 'C', '01']), list(['DIE', 'B', '02']),
       list(['DIE', 'A', '01']), list(['DIE', 'B', '01']),
       list(['DIE', 'B', '02']), list(['DIE', 'A', '01']),
       list(['DIE', 'B', '01']), list(['DIE', 'A', '02']),
       list(['DIE', 'A', '01']), list(['DIE', 'A', '02']),
       list(['DIE', 'A', '01']), list(['DIE', 'A', '02']),
       list(['DIE', 'A', '01']), list(['DIE', 'A', '02']),
       list(['DIE', 'A', '01']), list(['DIE', 'B', '02']),
       list(['DIE', 'B', '01']), list(['DIE', 'A', '01']),
       list(['DIE', 'B', '02']), list(['DIE', 'A', '01']),
       list(['DIE', 'A', '02']), list(['DIE', 'B', '01']),
       list(['DIE', 'A', '02']), list(['DIE', 'A', '02']),
       list(['DIE', 'A', '02']), list(['DIE', 'A', '01']),
       list(['DIE', 'B', '02']), list(['DIE', 'A', '01']),
       list(['DIE', 'B', '02']), list(['DIE', 'A', '01']),
       list(['DIE', 'A', '02']), list(['DIE', 'A', '02']),
       list(['DIE', 'A', '01']), list(['DIE', 'A', '01']),
       list(['DIE', 'A', '02']), list(['DIE', 'A', '02']),
       list(['DIE', 'B', '02']), list(['DIE', 'C', '01']),
       list(['DIE', 'A', '01']), list(['DIE', 'B', '01']),
       list(['DIE', 'A', '01']), list(['DIE', 'B', '02']),
       list(['DIE', 'A', '02']), list(['DIE', 'C', '01']),
       list(['DIE', 'B', '01']), list(['DIE', 'A', '01']),
       list(['DIE', 'A', '01']), list(['DIE', 'A', '01']),
       list(['DIE', 'B', '02']), list(['DIE', 'A', '01']),
       list(['DIE', 'A', '02']), list(['DIE', 'A', '02']),
       list(['DIE', 'A', '02']), list(['DIE', 'B', '02']),
       list(['DIE', 'A', '01']), list(['DIE', 'B', '02']),
       list(['DIE', 'B', '01']), list(['DIE', 'C', '01']),
       list(['DIE', 'B', '01']), list(['DIE', 'C', '01']),
       list(['DIE', 'A', '02']), list(['DIE', 'B', '01']),
       list(['DIE', 'B', '01']), list(['DIE', 'B', '02']),
       list(['DIE', 'C', '01']), list(['DIE', 'A', '01']),
       list(['DIE', 'A', '01']), list(['DIE', 'B', '01']),
       list(['DIE', 'B', '02']), list(['DIE', 'B', '01']),
       list(['DIE', 'A', '02']), list(['DIE', 'C', '01']),
       list(['DIE', 'A', '02']), list(['DIE', 'A', '01']),
       list(['DIE', 'A', '01']), list(['DIE', 'A', '01']),
       list(['DIE', 'B', '02']), list(['DIE', 'A', '01'])], dtype=object)

In [ ]:
# ('A')

In [ ]:
print(df['설비ID'].head(1).tolist())

['DIE-A-01']

In [ ]:
print(df['설비ID'].str.split('-').head(1).tolist())

[['DIE', 'A', '01']]

In [ ]:
linee= df['설비ID'].str.split('-').str[1]     
hogii= df['설비ID'].str.split('-').str[2]     
print("A호기 :", (linee =='A').sum(), "B호기 :", (linee =='B').sum(), "C호기 :", (linee =='C').sum())  
print((hogii =='01').sum(), (hogii =='02').sum())

A호기 : 111 B호기 : 74 C호기 : 15
114 86

In [ ]:
print(df['설비ID'].str.replace('DIE-', '', regex=False).head(1).tolist())

['A-01']

In [ ]:
df = pd.read_csv('c:/ex/data/설비 id.csv')

In [ ]:
df.head()

   설비ID
0  A-01
1  B-01
2  B-01
3  B-02
4  A-01

In [ ]:
df.info() #깃헙 푸시?

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   설비ID    200 non-null    str
dtypes: str(1)
memory usage: 2.5 KB

In [12]:
caution = df[df['품질등급'].isin(['주의','불량'])]
len(caution)

38

In [11]:
bisket = df[(df['비스킷두께'] > 10) & (df['비스킷두께'] < 16)]
len(bisket)

104

In [18]:
bisket = df[(df['비스킷두께'].between(10, 16))]
len(bisket)

117

In [17]:
linee= df['설비ID'].str.split('-').str[1]     
hogii= df['설비ID'].str.split('-').str[2]  


print(len(linee[linee =='A']))
print(len(hogii[(linee =='A') & (hogii =='1')]))

111
0

In [20]:
df.sort_values(['품질등급','사이클타임'], ascending=[True, False],)

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량
180  181  DIE-B-01  108.0   522.0   652.3   14.0  222.0   불량
181  182  DIE-C-01  214.0  1036.0    93.1   12.0  247.0   불량
190  191  DIE-B-02  238.0  1152.0    91.2   13.0  254.0   불량
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량
..   ...       ...    ...     ...     ...    ...    ...  ...
123  124  DIE-B-02  265.0   595.0    33.9   19.0  359.0   주의
124  125  DIE-A-01  265.0   595.0    33.8   19.0  355.0   주의
122  123  DIE-C-01  265.0   596.0    33.7   19.0  357.0   주의
89    90  DIE-A-02  235.0  1137.0    22.5    7.0  255.0   주의
42    43  DIE-A-01  215.0  1040.0    20.7   21.0  253.0   주의

[200 rows x 8 columns]

In [21]:
df.nlargest(5, '비스킷두께')

       샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
197  198  DIE-A-01  113.0   255.0   36.6   27.0  354.0   불량
191  192  DIE-B-01  113.0   255.0   36.9   26.0  366.0   불량
42    43  DIE-A-01  215.0  1040.0   20.7   21.0  253.0   주의
170  171  DIE-B-02  265.0   596.0   36.1   20.0  370.0   주의
196  197  DIE-A-01  265.0   595.0   36.2   20.0  355.0   불량

In [23]:
df.sort_values('비스킷두께', ascending=False).head(5)

       샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
197  198  DIE-A-01  113.0   255.0   36.6   27.0  354.0   불량
191  192  DIE-B-01  113.0   255.0   36.9   26.0  366.0   불량
42    43  DIE-A-01  215.0  1040.0   20.7   21.0  253.0   주의
170  171  DIE-B-02  265.0   596.0   36.1   20.0  370.0   주의
196  197  DIE-A-01  265.0   595.0   36.2   20.0  355.0   불량

In [24]:
df.sort_values('비스킷두께', ascending=False).head(5) == df.nlargest(5, '비스킷두께')

        샷  설비ID  실린더압력  주조압력  사이클타임  비스킷두께   형체력  품질등급
197  True  True   True  True   True   True  True  True
191  True  True   True  True   True   True  True  True
42   True  True   True  True   True   True  True  True
170  True  True   True  True   True   True  True  True
196  True  True   True  True   True   True  True  True

In [ ]:
df.nlargest(5, '비스킷두께') #실습4

       샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
197  198  DIE-A-01  113.0   255.0   36.6   27.0  354.0   불량
191  192  DIE-B-01  113.0   255.0   36.9   26.0  366.0   불량
42    43  DIE-A-01  215.0  1040.0   20.7   21.0  253.0   주의
170  171  DIE-B-02  265.0   596.0   36.1   20.0  370.0   주의
196  197  DIE-A-01  265.0   595.0   36.2   20.0  355.0   불량

In [29]:
df.sort_values(['품질등급','사이클타임'], ascending=[True, False]).head()

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량
180  181  DIE-B-01  108.0   522.0   652.3   14.0  222.0   불량
181  182  DIE-C-01  214.0  1036.0    93.1   12.0  247.0   불량
190  191  DIE-B-02  238.0  1152.0    91.2   13.0  254.0   불량
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량

In [30]:
print(df['샷'].head().tolist())

[1, 2, 3, 4, 5]

In [36]:
bullan = df[df['품질등급'] == '불량'].copy()
print(bullan.shape)

(20, 8)

In [39]:
bullan.head()

       샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
180  181  DIE-B-01  108.0   522.0  652.3   14.0  222.0   불량
181  182  DIE-C-01  214.0  1036.0   93.1   12.0  247.0   불량
182  183  DIE-A-02  215.0  1041.0   21.3    4.0  258.0   불량
183  184  DIE-B-01  216.0  1044.0   21.2   11.0  259.0   불량
184  185  DIE-B-01  219.0  1058.0   21.3    2.0  255.0   불량

In [40]:
bullan['위험등급'] = '높음'

In [51]:
bullan.shape

(20, 9)

In [50]:
bullan.replace('높음', 'High')
bullan.shape

(20, 9)

In [49]:
bullan.shape

(20, 9)

In [53]:
panjjj = df.copy()
#panjjj['라인'] = panjjj['설비ID'].str.split('-').str[1]

In [54]:
panjjj['설비ID'].str.split('-').str[1]

0      A
1      B
2      B
3      B
4      A
      ..
195    A
196    A
197    A
198    B
199    A
Name: 설비ID, Length: 200, dtype: object

In [56]:
panjjj['라인'] = panjjj['설비ID'].str.split('-').str[1]
panjjj.head()

   샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급 라인
0  1  DIE-A-01  214.0  1037.0   20.7   10.0  258.0   양품  A
1  2  DIE-B-01  217.0  1052.0   20.7   11.0  257.0   양품  B
2  3  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품  B
3  4  DIE-B-02  217.0  1052.0   20.6   11.0  253.0   양품  B
4  5  DIE-A-01  217.0  1052.0   20.6   11.0  254.0   양품  A

In [57]:
#panjjj.loc[panjjj['비스킷두께'] >=16, '두께판장'] = '높음'

In [59]:
panjjj.loc[panjjj['비스킷두께'] >=16]

       샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급 라인
42    43  DIE-A-01  215.0  1040.0   20.7   21.0  253.0   주의  A
67    68  DIE-B-02  215.0  1040.0   21.1   17.0  257.0   양품  B
108  109  DIE-A-01  264.0   594.0   36.4   18.0  363.0   양품  A
109  110  DIE-A-02  265.0   596.0   36.6   17.0  352.0   양품  A
110  111  DIE-A-02  264.0   595.0   37.0   18.0  361.0   양품  A
..   ...       ...    ...     ...    ...    ...    ...  ... ..
194  195  DIE-A-02  260.0   585.0   33.9   19.0  348.0   불량  A
195  196  DIE-A-01  264.0   594.0   76.3   19.0  381.0   불량  A
196  197  DIE-A-01  265.0   595.0   36.2   20.0  355.0   불량  A
197  198  DIE-A-01  113.0   255.0   36.6   27.0  354.0   불량  A
198  199  DIE-B-02  264.0   595.0   36.1   19.0  372.0   불량  B

[74 rows x 9 columns]

In [60]:
panjjj.loc[panjjj['비스킷두께'] >=16, '품질등급']

42     주의
67     양품
108    양품
109    양품
110    양품
       ..
194    불량
195    불량
196    불량
197    불량
198    불량
Name: 품질등급, Length: 74, dtype: str

In [64]:
panjjj.loc[panjjj['비스킷두께'] >=16, '두께판정'] = '두꺼움'
panjjj.head()

   샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급 라인 두께판정
0  1  DIE-A-01  214.0  1037.0   20.7   10.0  258.0   양품  A  NaN
1  2  DIE-B-01  217.0  1052.0   20.7   11.0  257.0   양품  B  NaN
2  3  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품  B  NaN
3  4  DIE-B-02  217.0  1052.0   20.6   11.0  253.0   양품  B  NaN
4  5  DIE-A-01  217.0  1052.0   20.6   11.0  254.0   양품  A  NaN

In [65]:
panjjj['여유형체력'] = panjjj['형체력'] - 250
panjjj.head()

   샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급 라인 두께판정  여유형체력
0  1  DIE-A-01  214.0  1037.0   20.7   10.0  258.0   양품  A  NaN    8.0
1  2  DIE-B-01  217.0  1052.0   20.7   11.0  257.0   양품  B  NaN    7.0
2  3  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품  B  NaN    4.0
3  4  DIE-B-02  217.0  1052.0   20.6   11.0  253.0   양품  B  NaN    3.0
4  5  DIE-A-01  217.0  1052.0   20.6   11.0  254.0   양품  A  NaN    4.0

In [67]:
df = pd.read_csv('c:/ex/data/13_diecasting_shot.csv') #실스5

In [69]:
dfcopy=df.copy()
dfcopy.head()

   샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
0  1  DIE-A-01  214.0  1037.0   20.7   10.0  258.0   양품
1  2  DIE-B-01  217.0  1052.0   20.7   11.0  257.0   양품
2  3  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
3  4  DIE-B-02  217.0  1052.0   20.6   11.0  253.0   양품
4  5  DIE-A-01  217.0  1052.0   20.6   11.0  254.0   양품

In [73]:
df.equals(dfcopy)

True

In [80]:
dfcopy.loc[dfcopy['비스킷두께'] >=16, '품질등급'] != '양품'
dfcopy.head()

   샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
0  1  DIE-A-01  214.0  1037.0   20.7   10.0  258.0   양품
1  2  DIE-B-01  217.0  1052.0   20.7   11.0  257.0   양품
2  3  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
3  4  DIE-B-02  217.0  1052.0   20.6   11.0  253.0   양품
4  5  DIE-A-01  217.0  1052.0   20.6   11.0  254.0   양품

In [96]:
len(dfcopy[(dfcopy['비스킷두께'] >=16) & (dfcopy['품질등급'] != '양품')])

25

In [101]:
dffiltertuple=dfcopy['비스킷두께'] >=16, '품질등급' != '양품'

In [102]:
dffilter= dfcopy[(dfcopy['비스킷두께'] >=16) & (dfcopy['품질등급'] != '양품')]

In [98]:
len(dffilter)

25

In [ ]:
dffilter.lar(5,'비스킷두께')

AttributeError: 'tuple' object has no attribute 'nlargest'

In [92]:
type(dffiltertuple)

tuple

In [93]:
type(df)

pandas.DataFrame

In [103]:
dffilter.nlargest(5,'비스킷두께')

       샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
197  198  DIE-A-01  113.0   255.0   36.6   27.0  354.0   불량
191  192  DIE-B-01  113.0   255.0   36.9   26.0  366.0   불량
42    43  DIE-A-01  215.0  1040.0   20.7   21.0  253.0   주의
170  171  DIE-B-02  265.0   596.0   36.1   20.0  370.0   주의
196  197  DIE-A-01  265.0   595.0   36.2   20.0  355.0   불량