In [1]:
print("Hello, world!")

Hello, world!

In [3]:
from importlib.metadata import distributions

for p in distributions():
    name = p.metadata['Name'] or ''
    if any(word in name.lower() for word in ['trans', 'korean', 'help', 'doc']):
        print(name, p.version)

In [6]:
import pandas as pd

In [139]:
df = pd.read_csv('c:/ex/data/13_diecasting_shot.csv')

In [140]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   샷       200 non-null    int64
 1   설비ID    200 non-null    str
 2   실린더압력   186 non-null    float64
 3   주조압력    186 non-null    float64
 4   사이클타임   186 non-null    float64
 5   비스킷두께   186 non-null    float64
 6   형체력     186 non-null    float64
 7   품질등급    200 non-null    str
dtypes: float64(5), int64(1), str(2)
memory usage: 12.6 KB

In [9]:
df.columns

Index(['샷', '설비ID', '실린더압력', '주조압력', '사이클타임', '비스킷두께', '형체력', '품질등급'], dtype='str')

In [17]:
df = pd.read_csv('c:/ex/data/13_diecasting_shot.csv')

In [27]:
two_column=df[['형체력', '실린더압력']]

In [28]:
two_column.shape

(200, 2)

In [29]:
list(df.columns)

['샷', '설비ID', '실린더압력', '주조압력', '사이클타임', '비스킷두께', '형체력', '품질등급']

In [30]:
two_column.head()

     형체력  실린더압력
0  258.0  214.0
1  257.0  217.0
2  254.0  214.0
3  253.0  217.0
4  254.0  217.0

In [31]:
type(two_column)

pandas.DataFrame

In [1]:
one_column = df['형체력']

NameError: name 'df' is not defined

In [33]:
one_column.
two_column.

0    258.0
1    257.0
2    254.0
3    253.0
4    254.0
Name: 형체력, dtype: float64

In [15]:
df.head()

   샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
0  1  DIE-A-01  214.0  1037.0   20.7   10.0  258.0   양품
1  2  DIE-B-01  217.0  1052.0   20.7   11.0  257.0   양품
2  3  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
3  4  DIE-B-02  217.0  1052.0   20.6   11.0  253.0   양품
4  5  DIE-A-01  217.0  1052.0   20.6   11.0  254.0   양품

In [16]:
df.index

RangeIndex(start=0, stop=200, step=1)

In [17]:
df[0:3]

   샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
0  1  DIE-A-01  214.0  1037.0   20.7   10.0  258.0   양품
1  2  DIE-B-01  217.0  1052.0   20.7   11.0  257.0   양품
2  3  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품

In [18]:
df.iloc[0]

샷               1
설비ID     DIE-A-01
실린더압력       214.0
주조압력       1037.0
사이클타임        20.7
비스킷두께        10.0
형체력         258.0
품질등급           양품
Name: 0, dtype: object

In [19]:
df.loc[0]

샷               1
설비ID     DIE-A-01
실린더압력       214.0
주조압력       1037.0
사이클타임        20.7
비스킷두께        10.0
형체력         258.0
품질등급           양품
Name: 0, dtype: object

In [21]:
df_copy=df.set_index('샷')

In [22]:
df.index

RangeIndex(start=0, stop=200, step=1)

In [27]:
df_copy.shape

(200, 7)

In [24]:
df_copy.iloc[0]

설비ID     DIE-A-01
실린더압력       214.0
주조압력       1037.0
사이클타임        20.7
비스킷두께        10.0
형체력         258.0
품질등급           양품
Name: 1, dtype: object

In [26]:
df_copy.head()

       설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
샷
1  DIE-A-01  214.0  1037.0   20.7   10.0  258.0   양품
2  DIE-B-01  217.0  1052.0   20.7   11.0  257.0   양품
3  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
4  DIE-B-02  217.0  1052.0   20.6   11.0  253.0   양품
5  DIE-A-01  217.0  1052.0   20.6   11.0  254.0   양품

In [28]:
df

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
0      1  DIE-A-01  214.0  1037.0    20.7   10.0  258.0   양품
1      2  DIE-B-01  217.0  1052.0    20.7   11.0  257.0   양품
2      3  DIE-B-01  214.0  1037.0    20.8   11.0  254.0   양품
3      4  DIE-B-02  217.0  1052.0    20.6   11.0  253.0   양품
4      5  DIE-A-01  217.0  1052.0    20.6   11.0  254.0   양품
..   ...       ...    ...     ...     ...    ...    ...  ...
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량
198  199  DIE-B-02  264.0   595.0    36.1   19.0  372.0   불량
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량

[200 rows x 8 columns]

In [29]:
df.sort_values(by='형체력')

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
180  181  DIE-B-01  108.0   522.0   652.3   14.0  222.0   불량
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량
186  187  DIE-C-01  108.0   524.0    22.9   14.0  247.0   불량
181  182  DIE-C-01  214.0  1036.0    93.1   12.0  247.0   불량
6      7  DIE-A-01  215.0  1038.0    20.9   11.0  250.0   양품
..   ...       ...    ...     ...     ...    ...    ...  ...
103  104  DIE-C-01    NaN     NaN     NaN    NaN    NaN   양품
104  105  DIE-A-01    NaN     NaN     NaN    NaN    NaN   양품
187  188  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량
188  189  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량
189  190  DIE-B-01    NaN     NaN     NaN    NaN    NaN   불량

[200 rows x 8 columns]

In [31]:
df_sorted_by_body=df.sort_values(by='형체력', ascending=False)

In [32]:
df_sorted_by_body.index[:4]

Index([171, 169, 166, 179], dtype='int64')

In [33]:
df_sorted_by_body.index[:4].to_list()

[171, 169, 166, 179]

In [147]:
df = pd.read_csv('c:/ex/data/13_diecasting_small.csv')

In [35]:
df_sorted_by_body  = df.sort_values('형체력', ascending=False)

In [37]:
df_sorted_by_body.index

Index([22, 17, 27, 12, 19,  0, 11, 13, 14, 16, 18, 15,  8,  1, 21, 20, 26, 23,
       25, 24, 28,  7,  6,  3,  2,  5, 29, 10,  9,  4],
      dtype='int64')

In [38]:
df_sorted_by_body.index[:4]

Index([22, 17, 27, 12], dtype='int64')

In [49]:
df_sorted_by_body.index[:4].to_list()

AttributeError: 'function' object has no attribute 'index'

In [47]:
df_sorted_by_body.head()

AttributeError: 'function' object has no attribute 'head'

In [46]:
df_sorted_by_body = df_sorted_by_body.reset_index(drop=True)

AttributeError: 'function' object has no attribute 'reset_index'

In [48]:
df_sorted_by_body = df_sorted_by_body.reset_index(drop=True)

AttributeError: 'function' object has no attribute 'reset_index'

In [50]:
df_sorted_by_body = df.sort_values('형체력', ascending=False)
df_sorted_by_body = df_sorted_by_body.reset_index(drop=True)

In [142]:
df.head()

   샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
0  1  DIE-A-01  214.0  1037.0   20.7   10.0  258.0   양품
1  2  DIE-B-01  217.0  1052.0   20.7   11.0  257.0   양품
2  3  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
3  4  DIE-B-02  217.0  1052.0   20.6   11.0  253.0   양품
4  5  DIE-A-01  217.0  1052.0   20.6   11.0  254.0   양품

In [53]:
df.loc[0:4]

   샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
0  1  DIE-B-02  214.0  1037.0   20.7   10.0  258.0   양품
1  2  DIE-C-01  217.0  1052.0   20.7   11.0  257.0   양품
2  3  DIE-A-02  215.0  1040.0   20.7   21.0  253.0   주의
3  4  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
4  5  DIE-C-01  108.0   522.0  652.3   14.0  222.0   불량

In [54]:
df = pd.read_csv('c:/ex/data/13_diecasting_small.csv')

In [55]:
df.head()

   샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
0  1  DIE-B-02  214.0  1037.0   20.7   10.0  258.0   양품
1  2  DIE-C-01  217.0  1052.0   20.7   11.0  257.0   양품
2  3  DIE-A-02  215.0  1040.0   20.7   21.0  253.0   주의
3  4  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
4  5  DIE-C-01  108.0   522.0  652.3   14.0  222.0   불량

In [56]:
df_bro=df.sort_values('형체력', ascending=False)

In [57]:
df_bro.head()

     샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
22  23  DIE-B-01  265.0   595.0   33.9   19.0  359.0   주의
17  18  DIE-A-02  265.0   596.0   33.7   19.0  357.0   주의
27  28  DIE-C-01  265.0   595.0   33.8   19.0  355.0   주의
12  13  DIE-A-02  265.0   596.0   33.9   19.0  354.0   주의
19  20  DIE-A-01  216.0  1044.0   21.2   11.0  259.0   불량

In [63]:
df.loc[0,'샷']

np.int64(1)

In [64]:
df.iloc[0]['샷']

np.int64(1)

In [65]:
정렬=df.sort_values('형체력', ascending=False)

In [67]:
print(정렬.loc[0, '샷'])     
print(정렬.iloc[0]['샷'])    # 23   — 설  설  설
print(정렬.index[:3].tolist())   # [22, 17, 27]

1
23
[22, 17, 27]

In [68]:
df.head()

   샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
0  1  DIE-B-02  214.0  1037.0   20.7   10.0  258.0   양품
1  2  DIE-C-01  217.0  1052.0   20.7   11.0  257.0   양품
2  3  DIE-A-02  215.0  1040.0   20.7   21.0  253.0   주의
3  4  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
4  5  DIE-C-01  108.0   522.0  652.3   14.0  222.0   불량

In [69]:
df.loc[0:4]

   샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
0  1  DIE-B-02  214.0  1037.0   20.7   10.0  258.0   양품
1  2  DIE-C-01  217.0  1052.0   20.7   11.0  257.0   양품
2  3  DIE-A-02  215.0  1040.0   20.7   21.0  253.0   주의
3  4  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
4  5  DIE-C-01  108.0   522.0  652.3   14.0  222.0   불량

In [70]:
df.loc[0:4,'형체력']

0    258.0
1    257.0
2    253.0
3    254.0
4    222.0
Name: 형체력, dtype: float64

In [73]:
df.loc[0:4,['실린더압력','형체력']]

   실린더압력    형체력
0  214.0  258.0
1  217.0  257.0
2  215.0  253.0
3  214.0  254.0
4  108.0  222.0

In [74]:
#17 샷 부터 20샷까지의 설비 id 사이클타임, 품질등급

In [86]:
df.loc[17:20,['설비ID','사이클타임','품질등급']]

        설비ID  사이클타임 품질등급
샷
17  DIE-A-02   21.0   양품
18  DIE-A-02   33.7   주의
19  DIE-A-02   20.8   양품
20  DIE-A-01   21.2   불량

In [126]:
df.loc[[3,7,15],['설비ID','사이클타임','품질등급']]

        설비ID  사이클타임 품질등급
샷
3   DIE-A-02   20.7   주의
7   DIE-B-02   20.6   양품
15  DIE-C-01   21.3   불량

In [143]:
df_shot_index = df.set_index('샷', inplace=True)

In [144]:
df.head()

       설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
샷
1  DIE-A-01  214.0  1037.0   20.7   10.0  258.0   양품
2  DIE-B-01  217.0  1052.0   20.7   11.0  257.0   양품
3  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
4  DIE-B-02  217.0  1052.0   20.6   11.0  253.0   양품
5  DIE-A-01  217.0  1052.0   20.6   11.0  254.0   양품

In [136]:
df.reset_index(inplace=True)

In [145]:
df_shot_index.head()

AttributeError: 'NoneType' object has no attribute 'head'

In [119]:
df_shot_index = df.set_index('샷', inplace=True)

In [146]:
df_shot_index = df.set_index('샷')
df_shot_index.head()

KeyError: "None of ['샷'] are in the columns"

In [148]:
df = pd.read_csv('c:/ex/data/13_diecasting_shot.csv')

In [149]:
df.head()

   샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
0  1  DIE-A-01  214.0  1037.0   20.7   10.0  258.0   양품
1  2  DIE-B-01  217.0  1052.0   20.7   11.0  257.0   양품
2  3  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
3  4  DIE-B-02  217.0  1052.0   20.6   11.0  253.0   양품
4  5  DIE-A-01  217.0  1052.0   20.6   11.0  254.0   양품

In [150]:
df.shape

(200, 8)

In [165]:
df_top=df.loc[0:9,['설비ID','비스킷두께','품질등급']]
df_top.head()

       설비ID  비스킷두께 품질등급
0  DIE-A-01   10.0   양품
1  DIE-B-01   11.0   양품
2  DIE-B-01   11.0   양품
3  DIE-B-02   11.0   양품
4  DIE-A-01   11.0   양품

In [163]:
df_down=df.loc[-5:]
df_down.head()

   샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
0  1  DIE-A-01  214.0  1037.0   20.7   10.0  258.0   양품
1  2  DIE-B-01  217.0  1052.0   20.7   11.0  257.0   양품
2  3  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
3  4  DIE-B-02  217.0  1052.0   20.6   11.0  253.0   양품
4  5  DIE-A-01  217.0  1052.0   20.6   11.0  254.0   양품