In [1]:
import numpy as np
import pandas as pd

In [2]:
Name	Gender	Age
Harry Potter	Male	23
David Baker	Male	31
John Smith	Male	22
Juan Martinez	Male	36
Jane Connor	Female	30

SyntaxError: invalid syntax (4022471227.py, line 1)

In [ ]:
John Smith	Intern	25000
Alex Du Bois	Team Lead	75000
Joanne Rowling	Manager	90000
Jane Connor	Manager	70000

In [33]:
chart1 = [{"name":"Harry Potter", "Gender" : "Male", "age" : 23},
        {"name":"David Baker", "Gender" : "Male", "age" : 31},
        {"name":"John Smith", "Gender" : "Male", "age" : 22},
        {"name":"Juan Martinez", "Gender" : "Male", "age" : 36},
        {"name":"Jane Connor", "Gender" : "Female", "age" : 30}]

print(*chart1, sep="\n")

{'name': 'Harry Potter', 'Gender': 'Male', 'age': 23}
{'name': 'David Baker', 'Gender': 'Male', 'age': 31}
{'name': 'John Smith', 'Gender': 'Male', 'age': 22}
{'name': 'Juan Martinez', 'Gender': 'Male', 'age': 36}
{'name': 'Jane Connor', 'Gender': 'Female', 'age': 30}

In [32]:
chart2 = [{"name":"John Smith", "Position":"Intern", "wage":25000 },
        {"name":"Alex Du Bois", "Position":"Team Lead", "wage":75000 },
        {"name":"Joanne Rowling", "Position":"Manager", "wage":90000 },
        {"name":"Jane Connor", "Position":"Manager", "wage":70000 }]

print(*chart2, sep="\n")

{'name': 'John Smith', 'Position': 'Intern', 'wage': 25000}
{'name': 'Alex Du Bois', 'Position': 'Team Lead', 'wage': 75000}
{'name': 'Joanne Rowling', 'Position': 'Manager', 'wage': 90000}
{'name': 'Jane Connor', 'Position': 'Manager', 'wage': 70000}

In [35]:
df = pd.DataFrame(chart1)
df

            name  Gender  age
0   Harry Potter    Male   23
1    David Baker    Male   31
2     John Smith    Male   22
3  Juan Martinez    Male   36
4    Jane Connor  Female   30

In [36]:
df2 = pd.DataFrame(chart2)
df2

             name   Position   wage
0      John Smith     Intern  25000
1    Alex Du Bois  Team Lead  75000
2  Joanne Rowling    Manager  90000
3     Jane Connor    Manager  70000

In [40]:
merged_df = pd.merge(df, df2, on="name",how="inner")
merged_df

          name  Gender  age Position   wage
0   John Smith    Male   22   Intern  25000
1  Jane Connor  Female   30  Manager  70000

In [42]:
merged_df = pd.merge(df, df2, on="name",how="left")
merged_df

            name  Gender  age Position     wage
0   Harry Potter    Male   23      NaN      NaN
1    David Baker    Male   31      NaN      NaN
2     John Smith    Male   22   Intern  25000.0
3  Juan Martinez    Male   36      NaN      NaN
4    Jane Connor  Female   30  Manager  70000.0

In [43]:
merged_df = pd.merge(df, df2, on="name",how="right")
merged_df

             name  Gender   age   Position   wage
0      John Smith    Male  22.0     Intern  25000
1    Alex Du Bois     NaN   NaN  Team Lead  75000
2  Joanne Rowling     NaN   NaN    Manager  90000
3     Jane Connor  Female  30.0    Manager  70000

In [44]:
merged_df = pd.merge(df, df2, on="name",how="outer")
merged_df

             name  Gender   age   Position     wage
0    Alex Du Bois     NaN   NaN  Team Lead  75000.0
1     David Baker    Male  31.0        NaN      NaN
2    Harry Potter    Male  23.0        NaN      NaN
3     Jane Connor  Female  30.0    Manager  70000.0
4  Joanne Rowling     NaN   NaN    Manager  90000.0
5      John Smith    Male  22.0     Intern  25000.0
6   Juan Martinez    Male  36.0        NaN      NaN