In [24]:
import pandas as pd

In [25]:
log = pd.read_csv('C:\\AI Equipment Failure Prediction\\data\\13_diecasting_shot.csv')
master = pd.read_csv('C:\\AI Equipment Failure Prediction\\data\\13_diecasting_master.csv')

In [26]:
log.head()

   샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
0  1  DIE-A-01  214.0  1037.0   20.7   10.0  258.0   양품
1  2  DIE-B-01  217.0  1052.0   20.7   11.0  257.0   양품
2  3  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
3  4  DIE-B-02  217.0  1052.0   20.6   11.0  253.0   양품
4  5  DIE-A-01  217.0  1052.0   20.6   11.0  254.0   양품

In [27]:
master.head()

       설비ID 라인  도입연도  정격형체력 담당반
0  DIE-A-01  A  2018    280  1반
1  DIE-A-02  A  2019    280  1반
2  DIE-B-01  B  2020    320  2반
3  DIE-B-02  B  2021    320  2반
4  DIE-D-01  D  2024    350  3반

In [28]:
three = log.head(3)[['샷', '설비ID', '비스킷두께']]
three

   샷      설비ID  비스킷두께
0  1  DIE-A-01   10.0
1  2  DIE-B-01   11.0
2  3  DIE-B-01   11.0

In [29]:
print(three.to_string(index=False))

 샷     설비ID  비스킷두께
 1 DIE-A-01   10.0
 2 DIE-B-01   11.0
 3 DIE-B-01   11.0

In [30]:
print(three.to_string(index=True))

   샷      설비ID  비스킷두께
0  1  DIE-A-01   10.0
1  2  DIE-B-01   11.0
2  3  DIE-B-01   11.0

In [31]:
pd.merge(master,log)

,설비ID,라인,도입연도,정격형체력,담당반,샷,실린더압력,주조압력,사이클타임,비스킷두께,형체력,품질등급
0,DIE-A-01,A,2018,280,1반,1,214.0,1037.0,20.7,10.0,258.0,양품
1,DIE-A-01,A,2018,280,1반,5,217.0,1052.0,20.6,11.0,254.0,양품
2,DIE-A-01,A,2018,280,1반,6,217.0,1052.0,20.6,11.0,257.0,양품
3,DIE-A-01,A,2018,280,1반,7,215.0,1038.0,20.9,11.0,250.0,양품
4,DIE-A-01,A,2018,280,1반,8,215.0,1038.0,20.9,11.0,258.0,양품
...,...,...,...,...,...,...,...,...,...,...,...,...
180,DIE-B-02,B,2021,320,2반,176,265.0,596.0,36.0,17.0,359.0,양품
181,DIE-B-02,B,2021,320,2반,178,264.0,595.0,36.0,17.0,355.0,양품
182,DIE-B-02,B,2021,320,2반,186,218.0,1054.0,21.4,2.0,253.0,불량
183,DIE-B-02,B,2021,320,2반,191,238.0,1152.0,91.2,13.0,254.0,불량
184,DIE-B-02,B,2021,320,2반,199,264.0,595.0,36.1,19.0,372.0,불량

In [32]:
three.merge(master, on=['설비ID'])

   샷      설비ID  비스킷두께 라인  도입연도  정격형체력 담당반
0  1  DIE-A-01   10.0  A  2018    280  1반
1  2  DIE-B-01   11.0  B  2020    320  2반
2  3  DIE-B-01   11.0  B  2020    320  2반

In [33]:
log.merge(master, on=['설비ID'])

,샷,설비ID,실린더압력,주조압력,사이클타임,비스킷두께,형체력,품질등급,라인,도입연도,정격형체력,담당반
0,1,DIE-A-01,214.0,1037.0,20.7,10.0,258.0,양품,A,2018,280,1반
1,2,DIE-B-01,217.0,1052.0,20.7,11.0,257.0,양품,B,2020,320,2반
2,3,DIE-B-01,214.0,1037.0,20.8,11.0,254.0,양품,B,2020,320,2반
3,4,DIE-B-02,217.0,1052.0,20.6,11.0,253.0,양품,B,2021,320,2반
4,5,DIE-A-01,217.0,1052.0,20.6,11.0,254.0,양품,A,2018,280,1반
...,...,...,...,...,...,...,...,...,...,...,...,...
180,196,DIE-A-01,264.0,594.0,76.3,19.0,381.0,불량,A,2018,280,1반
181,197,DIE-A-01,265.0,595.0,36.2,20.0,355.0,불량,A,2018,280,1반
182,198,DIE-A-01,113.0,255.0,36.6,27.0,354.0,불량,A,2018,280,1반
183,199,DIE-B-02,264.0,595.0,36.1,19.0,372.0,불량,B,2021,320,2반
184,200,DIE-A-01,108.0,525.0,6170.0,15.0,237.0,불량,A,2018,280,1반

In [34]:
merged=log.merge(master, on=['설비ID'], how='inner')

In [35]:
merged.shape

(185, 12)

In [36]:
merged_inner=log.merge(master, on=['설비ID'], how='inner')

In [37]:
merged_inner.shape

(185, 12)

In [38]:
merged_left=log.merge(master, on=['설비ID'], how='left')

In [39]:
merged_left.shape

(200, 12)

In [40]:
merged_outer=log.merge(master, on=['설비ID'], how='outer')

In [41]:
merged_outer.shape

(201, 12)

In [42]:
import pandas as pd
log = pd.read_csv('C:\\\\AI Equipment Failure Prediction\\data/13_diecasting_shot.csv')
master = pd.read_csv('C:\\\\AI Equipment Failure Prediction\\data/13_diecasting_master.csv')

In [43]:
print(log.shape)
print(master.shape)

(200, 8)
(5, 5)

In [44]:
log_copy = log.copy()
master_copy = master.copy()

In [45]:
print(log_copy.head())
print(master_copy.head())

   샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
0  1  DIE-A-01  214.0  1037.0   20.7   10.0  258.0   양품
1  2  DIE-B-01  217.0  1052.0   20.7   11.0  257.0   양품
2  3  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
3  4  DIE-B-02  217.0  1052.0   20.6   11.0  253.0   양품
4  5  DIE-A-01  217.0  1052.0   20.6   11.0  254.0   양품
       설비ID 라인  도입연도  정격형체력 담당반
0  DIE-A-01  A  2018    280  1반
1  DIE-A-02  A  2019    280  1반
2  DIE-B-01  B  2020    320  2반
3  DIE-B-02  B  2021    320  2반
4  DIE-D-01  D  2024    350  3반

In [46]:
merged=

SyntaxError: invalid syntax (1887154146.py, line 1)

In [ ]:
merged_inner=log.merge(master_copy, on=['설비ID'], how='inner')

In [ ]:
merged_copy=pd.merge(master_copy,log_copy)

In [ ]:
merged_copy

,설비ID,라인,도입연도,정격형체력,담당반,샷,실린더압력,주조압력,사이클타임,비스킷두께,형체력,품질등급
0,DIE-A-01,A,2018,280,1반,1,214.0,1037.0,20.7,10.0,258.0,양품
1,DIE-A-01,A,2018,280,1반,5,217.0,1052.0,20.6,11.0,254.0,양품
2,DIE-A-01,A,2018,280,1반,6,217.0,1052.0,20.6,11.0,257.0,양품
3,DIE-A-01,A,2018,280,1반,7,215.0,1038.0,20.9,11.0,250.0,양품
4,DIE-A-01,A,2018,280,1반,8,215.0,1038.0,20.9,11.0,258.0,양품
...,...,...,...,...,...,...,...,...,...,...,...,...
180,DIE-B-02,B,2021,320,2반,176,265.0,596.0,36.0,17.0,359.0,양품
181,DIE-B-02,B,2021,320,2반,178,264.0,595.0,36.0,17.0,355.0,양품
182,DIE-B-02,B,2021,320,2반,186,218.0,1054.0,21.4,2.0,253.0,불량
183,DIE-B-02,B,2021,320,2반,191,238.0,1152.0,91.2,13.0,254.0,불량
184,DIE-B-02,B,2021,320,2반,199,264.0,595.0,36.1,19.0,372.0,불량

In [ ]:
merged_inner=log.merge(master_copy, on=['설비ID'], how='inner')
merged_inner

,샷,설비ID,실린더압력,주조압력,사이클타임,비스킷두께,형체력,품질등급,라인,도입연도,정격형체력,담당반
0,1,DIE-A-01,214.0,1037.0,20.7,10.0,258.0,양품,A,2018,280,1반
1,2,DIE-B-01,217.0,1052.0,20.7,11.0,257.0,양품,B,2020,320,2반
2,3,DIE-B-01,214.0,1037.0,20.8,11.0,254.0,양품,B,2020,320,2반
3,4,DIE-B-02,217.0,1052.0,20.6,11.0,253.0,양품,B,2021,320,2반
4,5,DIE-A-01,217.0,1052.0,20.6,11.0,254.0,양품,A,2018,280,1반
...,...,...,...,...,...,...,...,...,...,...,...,...
180,196,DIE-A-01,264.0,594.0,76.3,19.0,381.0,불량,A,2018,280,1반
181,197,DIE-A-01,265.0,595.0,36.2,20.0,355.0,불량,A,2018,280,1반
182,198,DIE-A-01,113.0,255.0,36.6,27.0,354.0,불량,A,2018,280,1반
183,199,DIE-B-02,264.0,595.0,36.1,19.0,372.0,불량,B,2021,320,2반
184,200,DIE-A-01,108.0,525.0,6170.0,15.0,237.0,불량,A,2018,280,1반

In [ ]:
master.iloc[[0,0,1,2,3,4]]

       설비ID 라인  도입연도  정격형체력 담당반
0  DIE-A-01  A  2018    280  1반
0  DIE-A-01  A  2018    280  1반
1  DIE-A-02  A  2019    280  1반
2  DIE-B-01  B  2020    320  2반
3  DIE-B-02  B  2021    320  2반
4  DIE-D-01  D  2024    350  3반

In [ ]:
master_dup=master.iloc[[0,0,1,2,3,4]]

In [ ]:
master_dup['설비ID'].unique()

<ArrowStringArray>
['DIE-A-01', 'DIE-A-02', 'DIE-B-01', 'DIE-B-02', 'DIE-D-01']
Length: 5, dtype: str

In [ ]:
master_dup['설비ID'].nunique() #중복되지않는것만

5

In [ ]:
log.merge(master_dup, on='설비ID')

,샷,설비ID,실린더압력,주조압력,사이클타임,비스킷두께,형체력,품질등급,라인,도입연도,정격형체력,담당반
0,1,DIE-A-01,214.0,1037.0,20.7,10.0,258.0,양품,A,2018,280,1반
1,1,DIE-A-01,214.0,1037.0,20.7,10.0,258.0,양품,A,2018,280,1반
2,2,DIE-B-01,217.0,1052.0,20.7,11.0,257.0,양품,B,2020,320,2반
3,3,DIE-B-01,214.0,1037.0,20.8,11.0,254.0,양품,B,2020,320,2반
4,4,DIE-B-02,217.0,1052.0,20.6,11.0,253.0,양품,B,2021,320,2반
...,...,...,...,...,...,...,...,...,...,...,...,...
243,198,DIE-A-01,113.0,255.0,36.6,27.0,354.0,불량,A,2018,280,1반
244,198,DIE-A-01,113.0,255.0,36.6,27.0,354.0,불량,A,2018,280,1반
245,199,DIE-B-02,264.0,595.0,36.1,19.0,372.0,불량,B,2021,320,2반
246,200,DIE-A-01,108.0,525.0,6170.0,15.0,237.0,불량,A,2018,280,1반
247,200,DIE-A-01,108.0,525.0,6170.0,15.0,237.0,불량,A,2018,280,1반

In [ ]:
merged_innerr = log.merge(master, on='설비ID') #185 rows × 12 columns

In [ ]:
merged_left=log.merge(master, on='설비ID', how='left') #200 rows × 12 columns

In [ ]:
print(len(merged_innerr)-len(merged_left))

-15

In [ ]:
unmatched = merged_left[merged_left['라인'].isna()]
unmatched.shape

(15, 12)

In [ ]:
unmatched.head()

,샷,설비ID,실린더압력,주조압력,사이클타임,비스킷두께,형체력,품질등급,라인,도입연도,정격형체력,담당반
24,25,DIE-C-01,214.0,1037.0,20.7,11.0,257.0,양품,NaN,NaN,NaN,NaN
38,39,DIE-C-01,215.0,1040.0,20.9,11.0,257.0,양품,NaN,NaN,NaN,NaN
60,61,DIE-C-01,214.0,1037.0,20.6,11.0,254.0,양품,NaN,NaN,NaN,NaN
63,64,DIE-C-01,215.0,1040.0,20.6,11.0,254.0,양품,NaN,NaN,NaN,NaN
72,73,DIE-C-01,218.0,1057.0,21.2,13.0,257.0,양품,NaN,NaN,NaN,NaN

In [ ]:
log.iloc[:100]

      샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
0     1  DIE-A-01  214.0  1037.0   20.7   10.0  258.0   양품
1     2  DIE-B-01  217.0  1052.0   20.7   11.0  257.0   양품
2     3  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
3     4  DIE-B-02  217.0  1052.0   20.6   11.0  253.0   양품
4     5  DIE-A-01  217.0  1052.0   20.6   11.0  254.0   양품
..  ...       ...    ...     ...    ...    ...    ...  ...
95   96  DIE-B-01    NaN     NaN    NaN    NaN    NaN   양품
96   97  DIE-B-01    NaN     NaN    NaN    NaN    NaN   양품
97   98  DIE-B-01    NaN     NaN    NaN    NaN    NaN   양품
98   99  DIE-A-01    NaN     NaN    NaN    NaN    NaN   양품
99  100  DIE-A-02    NaN     NaN    NaN    NaN    NaN   양품

[100 rows x 8 columns]

In [ ]:
log.iloc[:100].reset_index().head()

   index  샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
0      0  1  DIE-A-01  214.0  1037.0   20.7   10.0  258.0   양품
1      1  2  DIE-B-01  217.0  1052.0   20.7   11.0  257.0   양품
2      2  3  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
3      3  4  DIE-B-02  217.0  1052.0   20.6   11.0  253.0   양품
4      4  5  DIE-A-01  217.0  1052.0   20.6   11.0  254.0   양품

In [ ]:
log.iloc[:100].reset_index(drop=True).head()

   샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
0  1  DIE-A-01  214.0  1037.0   20.7   10.0  258.0   양품
1  2  DIE-B-01  217.0  1052.0   20.7   11.0  257.0   양품
2  3  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
3  4  DIE-B-02  217.0  1052.0   20.6   11.0  253.0   양품
4  5  DIE-A-01  217.0  1052.0   20.6   11.0  254.0   양품

In [ ]:
part1 =log.iloc[:100].reset_index(drop=True)
part2 = log.iloc[100:].reset_index(drop=True)

In [ ]:
print(part1.shape)
print(part2.shape)

(100, 8)
(100, 8)

In [ ]:
pd.concat([part1, part2])

      샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
0     1  DIE-A-01  214.0  1037.0    20.7   10.0  258.0   양품
1     2  DIE-B-01  217.0  1052.0    20.7   11.0  257.0   양품
2     3  DIE-B-01  214.0  1037.0    20.8   11.0  254.0   양품
3     4  DIE-B-02  217.0  1052.0    20.6   11.0  253.0   양품
4     5  DIE-A-01  217.0  1052.0    20.6   11.0  254.0   양품
..  ...       ...    ...     ...     ...    ...    ...  ...
95  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량
96  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량
97  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량
98  199  DIE-B-02  264.0   595.0    36.1   19.0  372.0   불량
99  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량

[200 rows x 8 columns]

In [ ]:
stacked=pd.concat([part1, part2])

In [ ]:
stacked.index

Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       ...
       90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype='int64', length=200)

In [ ]:
stacked.index[97:100]

Index([97, 98, 99], dtype='int64')

In [ ]:
stacked.index[3:]

Index([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12,
       ...
       90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype='int64', length=197)

In [ ]:
stacked=pd.concat([part1, part2], ignore_index=True)

In [ ]:
#10:06까지 휴식

In [ ]:
part1.shape

(100, 8)

In [ ]:
master.shape

(5, 5)

In [ ]:
year = pd.concat([part1, part2], ignore_index=True)
year.shape

(200, 8)

In [ ]:
report = year.merge(master, on='설비ID', how='left')

In [ ]:
print(report['라인'].isna().sum())

15

In [ ]:
master.head()

       설비ID 라인  도입연도  정격형체력 담당반
0  DIE-A-01  A  2018    280  1반
1  DIE-A-02  A  2019    280  1반
2  DIE-B-01  B  2020    320  2반
3  DIE-B-02  B  2021    320  2반
4  DIE-D-01  D  2024    350  3반

In [ ]:
#1 실습3 1   ai 실습 챕터3 넘파이

In [ ]:
merged_left=log.merge(master, on='설비ID', how='left') #200 rows × 12 columns   
merged_left.shape

(200, 12)

In [55]:
with_line = merged_left[merged_left['라인'].notna()]

In [56]:
print(len(with_line))

185

In [62]:
nok=with_line[with_line['품질등급'] != '양품']
print(len(nok))

34

In [63]:
result=nok.sort_values('비스킷두께', ascending=False)

In [66]:
result.head()

,샷,설비ID,실린더압력,주조압력,사이클타임,비스킷두께,형체력,품질등급,라인,도입연도,정격형체력,담당반
197,198,DIE-A-01,113.0,255.0,36.6,27.0,354.0,불량,A,2018.0,280.0,1반
191,192,DIE-B-01,113.0,255.0,36.9,26.0,366.0,불량,B,2020.0,320.0,2반
42,43,DIE-A-01,215.0,1040.0,20.7,21.0,253.0,주의,A,2018.0,280.0,1반
196,197,DIE-A-01,265.0,595.0,36.2,20.0,355.0,불량,A,2018.0,280.0,1반
170,171,DIE-B-02,265.0,596.0,36.1,20.0,370.0,주의,B,2021.0,320.0,2반

In [ ]:
import pandas as pd

In [57]:
import pandas as pd

price = pd.read_excel('C:/AI Equipment Failure Prediction/data/Stock Data/stock price.xlsx')
valuation = pd.read_excel('C:/AI Equipment Failure Prediction/data/Stock Data/stock valuation.xlsx')

In [58]:
price.head()  #name, stock name  겹침 수정함

       id    name          value   price
0  128940    한미약품   59385.666667  421000
1  130960  CJ E&M   58540.666667   98900
2  138250   엔에스쇼핑   14558.666667   13200
3  139480     이마트  239230.833333  254500
4  142280  녹십자엠에스     468.833333   10200

In [59]:
valuation.head()

       id     name           eps     bps        per       pbr
0  130960   CJ E&M   6301.333333   54068  15.695091  1.829178
1  136480       하림    274.166667    3551  11.489362  0.887074
2  138040  메리츠금융지주   2122.333333   14894   6.313806  0.899691
3  139480      이마트  18268.166667  295780  13.931338  0.860437
4  145990      삼양사   5741.000000  108090  14.283226  0.758627

In [67]:
merged_prival = price.merge(valuation, on=['id', 'name'], how='outer').drop_duplicates()

In [80]:
merged_prival.round(2).head(100)

        id       name      value     price       eps       bps    per   pbr
0   128940       한미약품   59385.67  421000.0       NaN       NaN    NaN   NaN
1   130960     CJ E&M   58540.67   98900.0   6301.33   54068.0  15.70  1.83
2   136480         하림        NaN    3150.0    274.17    3551.0  11.49  0.89
3   138040    메리츠금융지주        NaN   13400.0   2122.33   14894.0   6.31  0.90
4   138250      엔에스쇼핑   14558.67   13200.0       NaN       NaN    NaN   NaN
5   139480        이마트  239230.83  254500.0  18268.17  295780.0  13.93  0.86
6   142280     녹십자엠에스     468.83   10200.0       NaN       NaN    NaN   NaN
7   145990        삼양사   82750.00   82000.0   5741.00  108090.0  14.28  0.76
8   161390      한국타이어        NaN   42100.0   5648.50   51341.0   7.45  0.82
9   181710  NHN엔터테인먼트        NaN   64900.0   2110.17   78434.0  30.76  0.83
10  185750        종근당   40293.67  100500.0   3990.33   40684.0  25.19  2.47
11  192400      쿠쿠홀딩스  179204.67  177500.0       NaN       NaN    NaN   NaN
12  199800         툴젠   -2514.33  115400.0       NaN       NaN    NaN   NaN
13  204210     모두투어리츠    3093.33    3475.0     85.17    5335.0  40.80  0.65
14  207940   삼성바이오로직스        NaN  417000.0   4644.17   60099.0  89.79  6.94

In [75]:
merged_prival[['name', 'price']]

         name     price
0        한미약품  421000.0
1      CJ E&M   98900.0
2          하림       NaN
3     메리츠금융지주       NaN
4       엔에스쇼핑   13200.0
5         이마트  254500.0
6      녹십자엠에스   10200.0
7         삼양사   82000.0
8       한국타이어       NaN
9   NHN엔터테인먼트       NaN
10        종근당  100500.0
11      쿠쿠홀딩스  177500.0
12         툴젠  115400.0
13     모두투어리츠    3475.0
14   삼성바이오로직스       NaN

In [76]:
# 계산한 주가만 별도 변수에 저장
calculated_price = merged_prival['eps'] * merged_prival['per']

# 기존 주가의 NaN을 채운 결과를 새 변수에 저장
filled_price = merged_prival['price'].fillna(calculated_price)

# NaN이 채워진 주가를 기존 데이터프레임에 반영
merged_prival['price'] = filled_price

In [78]:
# 원본을 유지하도록 표 복사
filled_df = merged_prival.copy()

# price의 결측값을 EPS × PER로 채우기
filled_df['price'] = filled_df['price'].fillna(
    filled_df['eps'] * filled_df['per']
)

# 전체 표 보기
display(filled_df)

,id,name,value,price,eps,bps,per,pbr
0,128940,한미약품,59385.666667,421000.0,NaN,NaN,NaN,NaN
1,130960,CJ E&M,58540.666667,98900.0,6301.333333,54068.0,15.695091,1.829178
2,136480,하림,NaN,3150.0,274.166667,3551.0,11.489362,0.887074
3,138040,메리츠금융지주,NaN,13400.0,2122.333333,14894.0,6.313806,0.899691
4,138250,엔에스쇼핑,14558.666667,13200.0,NaN,NaN,NaN,NaN
5,139480,이마트,239230.833333,254500.0,18268.166667,295780.0,13.931338,0.860437
6,142280,녹십자엠에스,468.833333,10200.0,NaN,NaN,NaN,NaN
7,145990,삼양사,82750.000000,82000.0,5741.000000,108090.0,14.283226,0.758627
8,161390,한국타이어,NaN,42100.0,5648.500000,51341.0,7.453306,0.820007
9,181710,NHN엔터테인먼트,NaN,64900.0,2110.166667,78434.0,30.755864,0.827447
10,185750,종근당,40293.666667,100500.0,3990.333333,40684.0,25.185866,2.470259
11,192400,쿠쿠홀딩스,179204.666667,177500.0,NaN,NaN,NaN,NaN
12,199800,툴젠,-2514.333333,115400.0,NaN,NaN,NaN,NaN
13,204210,모두투어리츠,3093.333333,3475.0,85.166667,5335.0,40.802348,0.651359
14,207940,삼성바이오로직스,NaN,417000.0,4644.166667,60099.0,89.790059,6.938551

| 컬럼 | 의미 |
|---|---|
| `name` | 회사명·종목명 |
| `value` | 회사가 돈 버는 능력(EPS)과 가진 순자산(BPS)을 함께 보고 주식 가치를 추정한다|
| `price` | 주가 |
| `eps` | 주당순이익 — 주식 1주당 순이익 |
| `bps` | 주당순자산 — 주식 1주당 순자산 |
| `per` | 주가수익비율 — **주가 ÷ EPS** |
| `pbr` | 주가순자산비율 — **주가 ÷ BPS** |

In [81]:
filled_df['value'] = filled_df['value'].fillna(
    (filled_df['eps'] * 10 + filled_df['bps']) / 2
)

display(filled_df)

,id,name,value,price,eps,bps,per,pbr
0,128940,한미약품,59385.666667,421000.0,NaN,NaN,NaN,NaN
1,130960,CJ E&M,58540.666667,98900.0,6301.333333,54068.0,15.695091,1.829178
2,136480,하림,3146.333333,3150.0,274.166667,3551.0,11.489362,0.887074
3,138040,메리츠금융지주,18058.666667,13400.0,2122.333333,14894.0,6.313806,0.899691
4,138250,엔에스쇼핑,14558.666667,13200.0,NaN,NaN,NaN,NaN
5,139480,이마트,239230.833333,254500.0,18268.166667,295780.0,13.931338,0.860437
6,142280,녹십자엠에스,468.833333,10200.0,NaN,NaN,NaN,NaN
7,145990,삼양사,82750.000000,82000.0,5741.000000,108090.0,14.283226,0.758627
8,161390,한국타이어,53913.000000,42100.0,5648.500000,51341.0,7.453306,0.820007
9,181710,NHN엔터테인먼트,49767.833333,64900.0,2110.166667,78434.0,30.755864,0.827447
10,185750,종근당,40293.666667,100500.0,3990.333333,40684.0,25.185866,2.470259
11,192400,쿠쿠홀딩스,179204.666667,177500.0,NaN,NaN,NaN,NaN
12,199800,툴젠,-2514.333333,115400.0,NaN,NaN,NaN,NaN
13,204210,모두투어리츠,3093.333333,3475.0,85.166667,5335.0,40.802348,0.651359
14,207940,삼성바이오로직스,53270.333333,417000.0,4644.166667,60099.0,89.790059,6.938551