In [2]:
import numpy as np

In [3]:
f = 'C:/ex/data/11_diecasting_series.csv'

In [4]:
ct = np.genfromtxt(f,   
                   delimiter=',',    
                   skip_header=1,    
                   usecols=1)        
print(ct.shape, ct.dtype)

(50,) float64

In [8]:
vib = np.array([2.1, 6.1, 2.0, 5.8])

pick = np.array([0,3])

In [1]:
print(vib[pick])

NameError: name 'vib' is not defined

In [10]:
vib = np.array([2.1, 6.1, 2.0, 5.8])

print(np.sort(vib))
print(np.argsort(vib))

[2.  2.1 5.8 6.1]
[2 0 3 1]

In [16]:
cycle = np.array([1, 2, 3, 4, 5])

In [17]:
vib = np.array([2.1, 6.1, 2.0, 5.8])

In [20]:
pos = np.argmax(vib)

In [21]:
print(cycle[pos])

2

In [22]:
cycle = np.array([1, 2, 3, 4, 5])
vib = np.array([2.1, 2.3, 6.1, 2.0, 5.8])
pos = np.argmax(vib)
print(cycle[pos])

3

In [23]:
cycle = np.array([1, 2, 3, 4, 5])
vib = np.array([2.1, 2.3, 6.1, 2.0, 5.8])

pos = np.argmax(vib)

print(vib.max())
print(pos)
print(cycle[pos])

6.1
2
3

In [25]:
f = 'C:/ex/data/11_diecasting_series.csv'
cyc = np.genfromtxt(f, delimiter=',', skip_header=1, usecols=0)
ct  = np.genfromtxt(f, delimiter=',', skip_header=1, usecols=1)

In [26]:
i = ct.argmax()

In [27]:
print(int(cyc[i]), ct[i])

50 6170.0

In [29]:
vib = np.array([2.0, 2.1, 2.2, 7.0, 7.1])
change = np.diff(vib)
print(np.round(change, 1))
print(np.argmax(change))

[0.1 0.1 4.8 0.1]
2

In [1]:
import numpy as np

In [2]:
change = np.array([0.1, -4.8, 4.8, -0.1])
print(np.abs(change))

[0.1 4.8 4.8 0.1]

In [3]:
import numpy as np

In [5]:
F = 'C:/ex/data/11_diecasting_series.csv'
cyc = np.genfromtxt(F, delimiter=',', skip_header=1, usecols=0)
ct  = np.genfromtxt(F, delimiter=',', skip_header=1, usecols=1)

In [8]:
change = np.abs(np.diff(ct))

In [9]:
j = change.argmax()

In [11]:
print(int(cyc[j]), int(cyc[j + 1]), round(change[j], 1))

49 50 6133.9

In [12]:
import numpy as np
pres = np.array([4.5, 9999.0, 4.6, -1.0])
fixed = np.clip(pres, 0, 10)
print(fixed)

[ 4.5 10.   4.6  0. ]

In [14]:
F = 'C:/ex/data/11_diecasting_series.csv'
cyl = np.genfromtxt(F, delimiter=',', skip_header=1, usecols=2)

In [15]:
cyl[0] = 9999

In [16]:
print(round(cyl.mean(), 1))

421.5

In [17]:
fixed = np.clip(cyl, 100, 300)
print(round(fixed.mean(), 1))

227.5

In [18]:
import numpy as np
defects = np.array([0, 1, 0, 2, 3, 5])
print(np.cumsum(defects))

[ 0  1  1  3  6 11]

In [19]:
vib = np.array([2.1, 3.5, 2.0, 6.2])
label = np.where(vib >= 5, 2, np.where(vib >= 3, 1, 0))
print(label)

[0 1 0 2]

In [21]:
import numpy as np
status = np.array([0, 0, 1, 0, 2, 1, 0])
kinds, counts = np.unique(status, return_counts=True)
print(kinds)
print(counts)

[0 1 2]
[4 2 1]

In [22]:
ct = np.genfromtxt(F, delimiter=',', skip_header=1, usecols=1)
label = np.where(ct >= 1000, 2, np.where(ct >= 50, 1, 0))
kinds, count = np.unique(label, return_counts=True)
print(kinds, count)              # [0 1 2] [46  2  2]
print(count / count.sum())

[0 1 2] [46  2  2]
[0.92 0.04 0.04]

In [23]:
import numpy as np
F = 'C:/ex/data/11_diecasting_series.csv'
def col(c):
    return np.genfromtxt(F, delimiter=',', skip_header=1, usecols=c)
cyc, ct, cyl = col(0), col(1), col(2)
i = ct.argmax()
print(int(cyc[i]), ct[i])                    # 50 6170.0
ch = np.abs(np.diff(ct)); j = ch.argmax()
print(int(cyc[j]), int(cyc[j + 1]))          # 49 50
warn = np.where((ct >= 50) | (cyl < 150), 1, 0)
print(round(warn.mean(), 2))                 # 0.12
top = np.argsort(ct)[::-1][:3]
print(cyc[top].astype(int))                  # [50 48 43]

50 6170.0
49 50
0.12
[50 48 43]

In [24]:
import numpy as np
F = 'C:/ex/data/11_diecasting_series.csv'
def col(c):
    return np.genfromtxt(F, delimiter=',', skip_header=1, usecols=c)
cyc, ct, cyl = col(0), col(1), col(2)
i = ct.argmax()
print(int(cyc[i]), ct[i])

50 6170.0

In [25]:
ch = np.abs(np.diff(ct)); j = ch.argmax()
print(int(cyc[j]), int(cyc[j + 1]))

49 50

In [26]:
warn = np.where((ct >= 50) | (cyl < 150), 1, 0)
print(round(warn.mean(), 2))                 # 0.12

0.12

In [27]:
top = np.argsort(ct)[::-1][:3]
print(cyc[top].astype(int))

[50 48 43]

In [28]:
import numpy as np
F = 'C:/ex/data/11_diecasting_series.csv'
ct = np.genfromtxt(F,
                   delimiter=',',   
                   skip_header=1,   
                   usecols=1)        
print(ct.shape, ct.dtype)

(50,) float64

In [30]:
cycle = np.array([1, 2, 3, 4, 5])
vib = np.array([2.1, 2.3, 6.1, 2.0, 5.8])
pos = np.argmin(vib)
print(cycle[pos])

4

In [31]:
import numpy as np
pres = np.array([4.5, 9999.0, 4.6, -1.0])
fixed = np.clip(pres, 0, 10)
print(fixed)

[ 4.5 10.   4.6  0. ]

In [32]:
import numpy as np
status = np.array([0, 0, 1, 0, 2, 1, 0])
counts = np.bincount(status)
print(counts)

[4 2 1]

In [33]:
a = np.array([0, 0, 2])

print(np.unique(a, return_counts=True))
# (array([0, 2]), array([2, 1]))

print(np.bincount(a))
# [2 0 1]

(array([0, 2]), array([2, 1]))
[2 0 1]

In [35]:
F = 'C:/ex/data/12_metro_compressor.csv' 
import csv

In [36]:
oil = []
with open(F, encoding='utf-8') as f:
    reader = csv.reader(f)
    next(reader)                        # 설설설  설설  설설설
    for row in reader:
        oil.append(float(row[4]) if row[4] else None)

In [37]:
import numpy as np

In [38]:
oil = np.genfromtxt(F,
                    delimiter=',',
                    skip_header=1,
                    usecols=4)

In [40]:
import pandas as pd

In [41]:
oil = pd.read_csv(F)['오일온도']

In [44]:
import pandas as pd     
df = pd.read_csv("C:/ex/data/12_metro_compressor.csv")
df.head()

                  측정시각  압축압력  배출압력  저장압력  오일온도  모터전류 가동상태
0  2020-02-27 06:38:47  9.30 -0.02  9.30  51.3  6.04   가동
1  2020-02-27 07:28:21  8.55 -0.02  8.55  56.8  0.04   정지
2  2020-02-27 08:17:54  8.67 -0.02  8.67  55.7  0.03   정지
3  2020-02-27 09:07:27  9.76 -0.02  9.76   NaN  3.81   가동
4  2020-02-27 09:57:01  8.49 -0.02  8.49  55.3  0.04   정지

In [46]:
import pandas as pd
df = pd.read_csv('C:/ex/data/12_metro_compressor.csv')

In [47]:
print(df.shape)     # (200, 7)
print(df.head())

(200, 7)
                  측정시각  압축압력  배출압력  저장압력  오일온도  모터전류 가동상태
0  2020-02-27 06:38:47  9.30 -0.02  9.30  51.3  6.04   가동
1  2020-02-27 07:28:21  8.55 -0.02  8.55  56.8  0.04   정지
2  2020-02-27 08:17:54  8.67 -0.02  8.67  55.7  0.03   정지
3  2020-02-27 09:07:27  9.76 -0.02  9.76   NaN  3.81   가동
4  2020-02-27 09:57:01  8.49 -0.02  8.49  55.3  0.04   정지

In [48]:
F = 'C:/ex/data/12_metro_compressor.csv'

In [52]:
sel = pd.read_csv(F, usecols=['측정시각', '오일온도', '모터전류'])

In [53]:
print(sel.shape)

(200, 3)

In [54]:
part = pd.read_csv(F, nrows=20)
print(part.shape)

(20, 7)

In [55]:
F = 'C:/ex/data/12_metro_compressor_semicolon.csv'

In [57]:
b = pd.read_csv(F, sep=';', encoding='utf-8')
print(b.shape)      # (200, 7)
print(b.columns)

(200, 7)
Index(['측정시각', '압축압력', '배출압력', '저장압력', '오일온도', '모터전류', '가동상태'], dtype='str')

In [58]:
df = pd.read_csv("c:/ex/data/12_metro_compressor.csv")

In [59]:
df.head()

                  측정시각  압축압력  배출압력  저장압력  오일온도  모터전류 가동상태
0  2020-02-27 06:38:47  9.30 -0.02  9.30  51.3  6.04   가동
1  2020-02-27 07:28:21  8.55 -0.02  8.55  56.8  0.04   정지
2  2020-02-27 08:17:54  8.67 -0.02  8.67  55.7  0.03   정지
3  2020-02-27 09:07:27  9.76 -0.02  9.76   NaN  3.81   가동
4  2020-02-27 09:57:01  8.49 -0.02  8.49  55.3  0.04   정지

In [61]:
df.tail(3)

                    측정시각  압축압력  배출압력  저장압력  오일온도  모터전류 가동상태
197  2020-03-06 16:42:06  9.74 -0.02  9.74  73.0  3.77   가동
198  2020-03-06 17:31:39  9.89 -0.02  9.89  72.5  3.82   가동
199  2020-03-06 18:21:13  9.87 -0.02  9.87  71.7  3.75   가동

In [63]:
import pandas as pd
df = pd.read_csv("c:/ex/data/12_metro_compressor.csv")

In [64]:
print(df.head(500).shape)   # (200, 7)

(200, 7)

In [65]:
df.index

RangeIndex(start=0, stop=200, step=1)

In [67]:
len(df.index)

200

In [69]:
d = pd.read_csv('c:/ex/data/12_metro_digital.csv',
                dtype={'압축기': str})

In [70]:
print(d['압축기'].dtype)

str

In [71]:
# CSV를 읽되, '압축기' 열은 문자열로 읽어서 d에 저장
d = pd.read_csv('c:/ex/data/12_metro_digital.csv', 
                dtype={'압축기': str})

In [72]:
d = pd.read_csv('c:/ex/data/12_metro_digital.csv') 
print(d.columns.tolist())

['측정시각', '압축기', '타워', '저압스위치']

In [73]:
print(d.dtypes)

측정시각       str
압축기      int64
타워       int64
저압스위치    int64
dtype: object

In [74]:
print(d.head())

                  측정시각  압축기  타워  저압스위치
0  2020-02-27 06:38:47    0   0      0
1  2020-02-27 07:28:21    1   1      0
2  2020-02-27 08:17:54    1   1      0
3  2020-02-27 09:07:27    1   1      0
4  2020-02-27 09:57:01    1   1      0

In [77]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   측정시각    200 non-null    str
 1   압축압력    200 non-null    float64
 2   배출압력    200 non-null    float64
 3   저장압력    200 non-null    float64
 4   오일온도    199 non-null    float64
 5   모터전류    200 non-null    float64
 6   가동상태    200 non-null    str
dtypes: float64(5), str(2)
memory usage: 15.9 KB
None

In [78]:
df = pd.read_csv('c:/ex/data/12_metro_compressor.csv')
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   측정시각    200 non-null    str
 1   압축압력    200 non-null    float64
 2   배출압력    200 non-null    float64
 3   저장압력    200 non-null    float64
 4   오일온도    199 non-null    float64
 5   모터전류    200 non-null    float64
 6   가동상태    200 non-null    str
dtypes: float64(5), str(2)
memory usage: 15.9 KB
None

In [79]:
print(len(df))

200

In [80]:
df.describe()

             압축압력        배출압력        저장압력        오일온도        모터전류
count  200.000000  200.000000  200.000000  199.000000  200.000000
mean     9.172200   -0.016950    9.171400   63.181910    2.060850
std      0.583699    0.047173    0.582497    6.249822    2.196505
min      8.130000   -0.030000    8.130000   50.100000    0.030000
25%      8.700000   -0.020000    8.697500   58.100000    0.040000
50%      9.175000   -0.020000    9.175000   62.900000    0.040000
75%      9.665000   -0.020000    9.655000   68.100000    3.812500
max     10.220000    0.600000   10.220000   75.000000    6.190000

In [81]:
state = df['가동상태'].values
cur = df['모터전류'].values
print(round(float(np.mean(cur[state == '가동'])), 2))   # 4.25

4.25

In [ ]:
# 가동상태 열을 NumPy 배열로 가져오기
state = df['가동상태'].values

# 모터전류 열을 NumPy 배열로 가져오기
cur = df['모터전류'].values

# '가동'인 행의 전류만 선택 → 평균 → 실수 변환 → 소수점 둘째 자리 반올림
print(round(float(np.mean(cur[state == '가동'])), 2))

In [82]:
print(df.describe().round(2))

         압축압력    배출압력    저장압력    오일온도    모터전류
count  200.00  200.00  200.00  199.00  200.00
mean     9.17   -0.02    9.17   63.18    2.06
std      0.58    0.05    0.58    6.25    2.20
min      8.13   -0.03    8.13   50.10    0.03
25%      8.70   -0.02    8.70   58.10    0.04
50%      9.18   -0.02    9.18   62.90    0.04
75%      9.66   -0.02    9.66   68.10    3.81
max     10.22    0.60   10.22   75.00    6.19

In [83]:
print(np.unique(state, return_counts=True))

(array(['가동', '정지'], dtype=object), array([ 96, 104]))

In [84]:
c = pd.read_csv('c:/ex/data/12_metro_compressor.csv')
d = pd.read_csv('c:/ex/data/12_metro_digital.csv')

In [85]:
c.info()
d.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   측정시각    200 non-null    str
 1   압축압력    200 non-null    float64
 2   배출압력    200 non-null    float64
 3   저장압력    200 non-null    float64
 4   오일온도    199 non-null    float64
 5   모터전류    200 non-null    float64
 6   가동상태    200 non-null    str
dtypes: float64(5), str(2)
memory usage: 15.9 KB
<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   측정시각    120 non-null    str
 1   압축기     120 non-null    int64
 2   타워      120 non-null    int64
 3   저압스위치   120 non-null    int64
dtypes: int64(3), str(1)
memory usage: 6.1 KB

In [86]:
sw = d['저압스위치'].values
print(np.unique(sw, return_counts=True))

(array([0]), array([120]))

In [88]:
s = pd.read_csv('c:/ex/data/12_metro_small.csv')
oil = s['오일온도'].values
cur = s['모터전류'].values

print('개요 : 지하철 공기압축기 측정 기록 - 압력 오일온도 모터전류')
print('크기 :', s.shape)
print('결측치 :', int(np.isnan(oil).sum()), '건  (오일온도)')
print('이상 신호 : 모터전류 평균 %.2f · 모터전류 중앙값 %.2f'
      % (np.mean(cur), np.median(cur)))
print('다음 할 일 : 가동상태로 나누어 두 상태를 따로보기')

개요 : 지하철 공기압축기 측정 기록 - 압력 오일온도 모터전류
크기 : (30, 7)
결측치 : 1 건  (오일온도)
이상 신호 : 모터전류 평균 1.38 · 모터전류 중앙값 0.04
다음 할 일 : 가동상태로 나누어 두 상태를 따로보기

가상환경 설정

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt